.vscode/settings.json, package.json, src/farcasterNode.ts, src/server.ts, tsconfig.json, yarn.lock
Create a set of simple Farcaster Node instances that can ping-pong each other pseudo-randomly once started.
=> feat: ping-pong nodes

src/engine/engine.root.test.ts, src/engine/index.ts, src/utils.test.ts, src/utils.ts, yarn.lock
per https://github.com/farcasterxyz/node-playground/issues/21 we want to devise an algorithm for predictable root hash processing. We compare hashes based on their ascii value taking the one with the lower hash.
=> added lexicographical hash comparing for roots

src/engine/engine.verification.test.ts, src/sets/verificationSet.test.ts
Decreased test time from ~8.7 seconds to ~4.9 seconds
=> Faster Verification Set Tests

Dockerfile
Fixes #62 
Adds a Dockerfile to the repo, builds and runs `yarn server` on run.
=> feat: Add Dockerfile for containerized builds

package-lock.json, package.json, src/engine/index.ts, src/network/rpc.test.ts, src/network/rpc.ts, src/sets/castSet.ts, src/sets/signerSet.ts, yarn.lock
https://github.com/farcasterxyz/hub/issues/98 Need a mechanism to communicate between Hubs and to be able to serve data to clients.
Created a JSON RPC server and client. 
Added the ability to transfer `CastSet`s, `FID`s, and `SignerSet`s.
=> feat: Implement a JSON RPC server and client

package.json, src/engine/index.ts, src/factories.ts, src/network/rpc.test.ts, src/network/rpc.ts, src/sets/castSet.ts, src/sets/followSet.ts, src/sets/reactionSet.ts, src/sets/signerSet.ts, src/sets/verificationSet.ts
Added RPC APIs for the remaining Sets in the engine. 
Refactored API names a bit
=> feat: Add RPC getters for all Sets

src/engine/index.ts, src/network/rpc.test.ts
Adds a convenience API to merge a list of messages
=> feat: Add a convenience API to merge a list of Messages

package.json, yarn.lock
Keep packages up to date to avoid drift.
Updated all minor and patch packages except faker (which has repo issues) and libp2p (which I didn't want to do without checking with @sagar-a16z )
=> chore: update packages (sep 2022)

package.json, src/engine/engine.mock.test.ts, src/engine/index.ts, src/engine/mock.ts, src/hub.test.ts, src/hub.ts, src/network/node.test.ts, src/network/node.ts, src/network/protocol.test.ts, src/network/protocol.ts, src/network/rpc.test.ts, src/network/rpc.ts, src/network/rpcSync.test.ts, src/network/typeguards.ts, yarn.lock
We need a class definition for the `Hub` object. 
A Hub is made up of a collection of services (RPC, GossipSub, Engine...) that together implement all of its behaviors.
fixes https://github.com/farcasterxyz/hub/issues/64
Created a Hub class.
- Pulled in PubSub peer discovery to run alongside gossip to keep the libp2p peerlist up to date
- Added new RPC API to Publish messages to Hubs (Hubs will then publish those to the rest of the network via Gossip)
- Added support for bootstrapping a Hub off of a list of other Hub addresses. https://github.com/farcasterxyz/hub/issues/64
- Wrote a test that bootstraps a Hub off of an existing Hub on a network. 
Note - we need a lot more tests here as we flesh out more features. Filed https://github.com/farcasterxyz/hub/issues/129
_Choose all relevant …
=> feat: Hubs

src/network/node.test.ts
Fixes linter error introduced in https://github.com/farcasterxyz/hub/pull/130#discussion_r984959387
=> fix: unused variable lint error

package.json, src/hub.test.ts, src/hub.ts, src/server.ts, yarn.lock
Need a Hub executable
Add CLI parsing to `server.ts` and integrate Hub.
=> feat: hub executable

src/sets/signerSet.test.ts, src/sets/signerSet.ts
Reviewed and audited the SignerSet with the goal of increasing coverage, catching errors and improving readability
The refactor addresses the following issues: 
- Improves coverage for uncovered methods, branches and states
- Fixes a test that was triggering and asserting success on an incorrect failure
- Rewrite some class documentation and test names for clarity
=> test(SignerSet): improve coverage, fix incorrect assertions, update class documentation

.eslintrc.cjs, Dockerfile, package.json, yarn.lock
=> chore: add eslint-plugin-security to linting to catch security issues

package.json, yarn.lock
Dependency does not appear used anywhere
=> chore: remove unused dep node-fetch

src/hub.ts, src/network/p2p/node.ts, src/network/rpc/server.ts, src/utils/logger.ts
Updated logs in hub, node, and rpc to carry component and context information where applicable. 
=> chore: add more detail to hub, node, and rpc logs

src/cli.ts
Allow generating multiple PeerIds from the cli
=> feat: Generate multiple PeerIds

Dockerfile, src/hub.ts
=> fix: update dockerfile to specify rpc and p2p ports

Dockerfile
unable to start Docker container
fix incorrect parameter name, copy config files to docker image
=> fix(dockerfile): execute the hub process with the right config options

Dockerfile
debug deploy by increasing network timeout to 30 min 
=> chore: debug deploy by increasing network timeout to 30 min

src/storage/sets/flatbuffers/castSet.ts
`hash` is used in the CastSet in places where the value should be `tsHash`
Renames `hash` to `TsHash` where appropriate. Some instances of `hash` require changes to the IDL, which will be done in a follow on PR.
=> refactor(CastSet): rename hash to tsHash

src/storage/db/reaction.ts, src/storage/sets/flatbuffers/reactionStore.test.ts, src/storage/sets/flatbuffers/reactionStore.ts
=> refactor(reactionSet): rename to ReactionStore

src/network/p2p/connectionFilter.ts
Add debug logs to see why healthchecks on AWS are failing
=> fix(libp2p): add debug logs

src/hub.ts, src/network/rpc/client.ts, src/network/sync/syncEngine.ts, src/storage/engine/index.ts, src/test/perf/scenario.ts, src/test/perf/utils.ts
Improve the bench client's max throughput from ~200 msgs/s to ~3000 msgs/s
=> fix(benchmark): improve the bench client's throughput

src/network/rpc/rpc.test.ts, src/test/perf/scenario.ts, src/test/perf/utils.ts
=> chore: Add test coverage for batched submissions

src/network/rpc/server.ts
=> change rpc to IPv4 by default

src/storage/sets/flatbuffers/signerStore.test.ts
Fixes situations where variables were named incorrectly, wrong factory types were used and wrong casts were made. None of these issues affected the correctness of the tests.
=> test(SignerStore): fix incorrect variable names and casts

README.md
#fixes https://github.com/farcasterxyz/hub/issues/182
Added instructions to make sure a PeerID is created before running `yarn start`. 
=> chore(readme): document identity creation step

src/storage/sets/flatbuffers/followStore.ts, src/storage/sets/flatbuffers/reactionStore.ts, src/storage/sets/flatbuffers/signerStore.ts, src/storage/sets/flatbuffers/userDataStore.test.ts, src/storage/sets/flatbuffers/userDataStore.ts, src/storage/sets/flatbuffers/verificationStore.ts
Some branches in the user data store were not covered by tests
Add missing test coverage and makes minor improvements to documentation.
=> test(UserDataStore): increase test coverage

src/network/rpc/flatbuffers/server.ts
Allow configuring the gRpc server's port
=> feat: configure gRpc port

README.md
Spaces are good.
I added a space
=> documentation: Add space to README.md

src/storage/flatbuffers/messageModel.test.ts, src/storage/flatbuffers/messageModel.ts, src/storage/flatbuffers/types.ts, src/storage/sets/flatbuffers/castStore.ts, src/storage/sets/flatbuffers/followStore.test.ts, src/storage/sets/flatbuffers/followStore.ts, src/utils/generated/message_generated.ts, src/utils/schemas/message.fbs
Prune messages from follow store.
* Add `pruneMessages` method to follow store
* Update `MessageModel` to throw if flatbuffer has missing type
=> feat: follow store pruning 

src/storage/sets/flatbuffers/followStore.test.ts, src/storage/sets/flatbuffers/followStore.ts, src/storage/sets/flatbuffers/reactionStore.test.ts, src/storage/sets/flatbuffers/reactionStore.ts
Implement pruning for reactions.
* Add `pruneMessages` method for the reaction store
* Default limits to 5000 messages or 90 days for reaction store
* Correct default in follow store to remove the time-based limit
=> feat: add pruneMessages method to ReactionStore

src/storage/engine/flatbuffers/index.test.ts, src/storage/engine/flatbuffers/index.ts
Restoring "old world" functionality.
small change to add some metrics to the engine's merging methods
=> chore: add mergeMessages and metrics to engine

src/cli.ts, src/flatbuffers/hub.ts, src/network/rpc/flatbuffers/server.ts, src/network/rpc/flatbuffers/submitService.ts
fixes https://github.com/farcasterxyz/hub/issues/281
- Created a Hub class for Flatbuffers. 
- This class has no Sync or Gossip implementation for now. 
- Replaced the Hub that the `cli` script starts up. 
=> feat: flatbuffers Hub class

src/flatbuffers/hub.ts, src/hub.ts, src/network/p2p/flatbuffers/node.test.ts, src/network/p2p/flatbuffers/node.ts, src/network/rpc/flatbuffers/ampService.test.ts, src/network/rpc/flatbuffers/castService.test.ts, src/network/rpc/flatbuffers/client.ts, src/network/rpc/flatbuffers/eventService.test.ts, src/network/rpc/flatbuffers/reactionService.test.ts, src/network/rpc/flatbuffers/server.ts, src/network/rpc/flatbuffers/signerService.test.ts, src/network/rpc/flatbuffers/submitService.test.ts, src/network/rpc/flatbuffers/syncService.test.ts, src/network/rpc/flatbuffers/userDataService.test.ts, src/network/rpc/flatbuffers/verificationService.test.ts, src/test/factories/flatbuffer.test.ts, src/test/factories/flatbuffer.ts, src/utils/p2p.ts
Rebasing and merging @sagar-a16z 's PR: https://github.com/farcasterxyz/hub/pull/292
See above
=> feat: implement gossip node for flatbuffer messages

src/flatbuffers/utils/bytes.ts, src/rpc/test/submitService.test.ts, src/storage/engine/index.test.ts, src/storage/engine/index.ts
Adds more specific logs to help debug errors
Returns the specific fid that was not found when unknown user error is encountered
=> chore: add fid to unknown user error for debugging

src/flatbuffers/utils/eip712.ts, src/rpc/client/index.ts, src/rpc/server/index.ts, src/rpc/serviceDefinitions/ampDefinition.ts, src/rpc/serviceDefinitions/castDefinition.ts, src/rpc/serviceDefinitions/eventDefinition.ts, src/rpc/serviceDefinitions/reactionDefinition.ts, src/rpc/serviceDefinitions/signerDefinition.ts, src/rpc/serviceDefinitions/submitDefinition.ts, src/rpc/serviceDefinitions/syncDefinition.ts, src/rpc/serviceDefinitions/userDataDefinition.ts, src/rpc/serviceDefinitions/verificationDefinition.ts
Backporting minor changes that had to be made to keep the rpc client compatible with the backend repo 
=> refactor: backport minor changes to rpc client, libs

src/network/p2p/node.ts, yarn.lock
Keeping libp2p up to date
All minor and patch versions were updated, major versions will be handled in a follow-on PR.
=> chore: upgrade minor + patch versions of libp2p

CONTRIBUTING.md, package.json
Fix flatc generation after the folder structure change.
Redo the `yarn flatc` generation command
=> fix: flatc generation

app/src/eth/ethEventsProvider.test.ts, app/src/flatbuffers/models/idRegistryEventModel.test.ts, app/src/flatbuffers/models/nameRegistryEventModel.test.ts, app/src/hub.ts, app/src/network/sync/merkleTrie.ts, app/src/network/sync/multiPeerSyncEngine.test.ts, app/src/network/sync/syncEngine.ts, app/src/utils/contractEvent.ts
Some of our imports used relative paths rather than ~ paths.
Replace relative paths with ~ paths.
=> fix: replace relative paths with ~ paths

packages/js/README.md, packages/js/package.json, packages/js/src/index.ts
Preparing `@farcaster/js` package for npm publishing
=> chore: add readme to @farcaster/js

apps/hub/src/hub.ts, apps/hub/src/network/p2p/gossipNode.ts
When a hub first starts up and connects to peers, attempt to sync
- Gossip out a node's RPC and gossip addresses
- When connecting, perform sync with a new node
- Cleanup when disconnecting from a node
=> fix: Sync when first connecting to a node

README.md, packages/grpc/README.md, packages/js/README.md, packages/utils/README.md
=> chore: add readme to all packages and update @farcaster/js docs with comments

apps/hub/src/cli.ts
=> fix: cli should parse network arg correctly

packages/js/src/builders.test.ts, packages/js/src/builders.ts, packages/js/src/index.ts, packages/js/src/signers.ts, packages/js/src/types.ts
=> feat: add message data builders

README.md, apps/hub/README.md
Fix outdated content in README
- fix broken link in project README
- update starting command arguments in hub's README
=> chore: update README

apps/hub/src/console/castsCommand.ts, apps/hub/src/console/infoCommand.ts, apps/hub/src/console/syncTrieCommand.ts
Import from packages instead of relative directories
- Fix import statements
=> fix: Import from packages

apps/hub/src/console/castsCommand.ts, apps/hub/src/console/console.ts, apps/hub/src/console/infoCommand.ts, apps/hub/src/console/syncTrieCommand.ts
Cleanup the console command classes
- Add Command Interface 
- Add detailed help text to each command. 
=> chore: Cleanup command classes

.changeset/dry-vans-drop.md, apps/protohub/src/storage/db/idRegistryEvent.test.ts, apps/protohub/src/storage/db/idRegistryEvent.ts, apps/protohub/src/storage/db/message.test.ts, apps/protohub/src/storage/db/message.ts, apps/protohub/src/storage/db/types.ts, apps/protohub/src/storage/engine/index.test.ts, apps/protohub/src/storage/engine/index.ts, apps/protohub/src/storage/engine/seed.ts, apps/protohub/src/storage/stores/reactionStore.test.ts, apps/protohub/src/storage/stores/reactionStore.ts, apps/protohub/src/storage/stores/sequentialMergeStore.test.ts, apps/protohub/src/storage/stores/signerStore.test.ts, apps/protohub/src/storage/stores/signerStore.ts, apps/protohub/src/storage/stores/storeEventHandler.ts, apps/protohub/src/storage/stores/utils.ts, packages/protobufs/src/generated/id_registry_event.ts, packages/protobufs/src/index.ts, packages/protobufs/src/schemas/id_registry_event.proto, packages/protoutils/src/factories.test.ts, packages/protoutils/src/factories.ts
=> feat: protobufs signer store

apps/protohub/src/storage/db/message.ts, apps/protohub/src/storage/engine/index.test.ts, apps/protohub/src/storage/engine/index.ts, apps/protohub/src/storage/stores/castStore.test.ts, apps/protohub/src/storage/stores/castStore.ts, apps/protohub/src/storage/stores/reactionStore.ts
=> feat: protobufs cast store

apps/protohub/src/storage/engine/index.test.ts, apps/protohub/src/storage/engine/index.ts, apps/protohub/src/storage/stores/ampStore.test.ts, apps/protohub/src/storage/stores/ampStore.ts
=> feat: add protobufs amp store

.changeset/early-fireants-approve.md, apps/protohub/src/network/sync/syncEngine.test.ts, apps/protohub/src/storage/db/nameRegistryEvent.test.ts, apps/protohub/src/storage/db/nameRegistryEvent.ts, apps/protohub/src/storage/engine/index.test.ts, apps/protohub/src/storage/engine/index.ts, apps/protohub/src/storage/stores/storeEventHandler.ts, apps/protohub/src/storage/stores/userDataStore.test.ts, apps/protohub/src/storage/stores/userDataStore.ts, apps/protohub/src/storage/stores/utils.ts, packages/protobufs/src/generated/name_registry_event.ts, packages/protobufs/src/index.ts, packages/protobufs/src/schemas/name_registry_event.proto, packages/protoutils/src/factories.test.ts, packages/protoutils/src/factories.ts
=> add protobufs user data store

apps/protohub/src/network/sync/syncEngine.test.ts, apps/protohub/src/rpc/server/index.ts, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/schemas/rpc.proto
Fix some typos
- Change RPC names to fix typos
=> fix: typos in RPC definitions

apps/protohub/src/network/sync/syncEngine.ts, apps/protohub/src/storage/engine/index.test.ts, apps/protohub/src/storage/engine/index.ts, apps/protohub/src/storage/stores/verificationStore.test.ts, apps/protohub/src/storage/stores/verificationStore.ts, yarn.lock
=> feat: add protobufs verification store

apps/protohub/src/storage/db/nameRegistryEvent.test.ts
=> fix: nameRegistryEvent test using duplicate db name

.changeset/clever-trains-shake.md, apps/protohub/src/storage/db/idRegistryEvent.ts, apps/protohub/src/storage/db/message.ts, apps/protohub/src/storage/jobs/pruneMessagesJob.test.ts, apps/protohub/src/storage/jobs/pruneMessagesJob.ts, apps/protohub/src/storage/jobs/revokeSignerJob.test.ts, apps/protohub/src/storage/jobs/revokeSignerJob.ts, apps/protohub/src/storage/jobs/utils/factories.ts, apps/protohub/src/storage/stores/ampStore.ts, apps/protohub/src/storage/stores/castStore.ts, apps/protohub/src/storage/stores/reactionStore.ts, apps/protohub/src/storage/stores/signerStore.ts, packages/protobufs/src/generated/job.ts, packages/protobufs/src/index.ts, packages/protobufs/src/schemas/job.proto
=> feat: add protobuf job implementation

.changeset/six-melons-tease.md, apps/protohub/src/storage/jobs/revokeSignerJob.test.ts, packages/protoutils/src/crypto/ed25519.test.ts, packages/protoutils/src/crypto/eip712.test.ts, packages/protoutils/src/factories.ts, packages/protoutils/src/signers/ed25519Signer.test.ts, packages/protoutils/src/signers/eip712Signer.test.ts, packages/protoutils/src/validations.test.ts, packages/protoutils/src/validations.ts
=> fix: enforce fixed size for protobuf addresses and hashes and fix flaky test

apps/protohub/src/hub.ts, apps/protohub/src/network/sync/syncEngine.test.ts, apps/protohub/src/network/sync/syncEngine.ts, apps/protohub/src/rpc/server/index.ts, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/index.ts, packages/protobufs/src/schemas/rpc.proto
Wire up the RPC server.
- Wire up the RPC server
- Small changes to protobuf format for sync methods to prevent unnecessary conversions
The tests for the RPC server are not in this PR, will follow up in a separate PR
=> feat: Wire up RPC server

apps/protohub/src/eth/ethEventsProvider.ts, apps/protohub/src/hub.ts, apps/protohub/src/rpc/server/index.ts, apps/protohub/src/utils/logger.ts, packages/protobufs/src/index.ts
Move the Hub class to protobufs
- Move hub.ts to protobufs
- Create server class to start/stop
=> feat: Move Hub to protobufs

apps/protohub/src/rpc/client/index.ts, apps/protohub/src/rpc/server/test/castService.test.ts, apps/protohub/src/storage/engine/index.ts, apps/protohub/src/storage/jobs/revokeSignerJob.test.ts, packages/protoutils/src/validations.test.ts, packages/protoutils/src/validations.ts
Add CastServiceTests
- Tests for Cast service
- Add fid validations
=> tests: Add CastService tests

apps/protohub/src/cli.ts, apps/protohub/src/console/castsCommand.ts, apps/protohub/src/console/console.ts, apps/protohub/src/console/infoCommand.ts, apps/protohub/src/console/syncTrieCommand.ts, apps/protohub/src/utils/command.ts
Move `cli.ts` and the debug console to protohubs
- Move console to using protos
- Move cli.ts
=> feat: Move debug console and cli.ts

apps/protohub/src/rpc/server/test/verificationService.test.ts, apps/protohub/src/storage/engine/index.ts
Verification Service test for protohubs
- Add verifications to params
- Verification Service test for protohubs
=> feat: verification service test

CONTRIBUTING.md
Improve precision of documentation
Update documentation to refer to directory in code
=> docs: update documentation to match code

apps/protohub/src/cli.ts, apps/protohub/src/eth/abis.ts, apps/protohub/src/eth/ethEventsProvider.test.ts, apps/protohub/src/eth/ethEventsProvider.ts, apps/protohub/src/eth/utils.test.ts, apps/protohub/src/eth/utils.ts, apps/protohub/src/hub.ts
=> chore: port ethEventsProvider to protobufs

apps/protohub/src/eth/ethEventsProvider.ts, apps/protohub/src/hub.ts, apps/protohub/src/storage/db/hubState.ts, apps/protohub/src/utils/logger.ts, packages/protobufs/src/schemas/hub_state.proto
=> chore: port hub state to protobufs

.changeset/clean-hats-march.md, .changeset/clever-trains-shake.md, .changeset/dry-vans-drop.md, .changeset/early-fireants-approve.md, .changeset/honest-ghosts-cover.md, .changeset/six-melons-tease.md, .changeset/tiny-experts-check.md, apps/hub/CHANGELOG.md, apps/hub/package.json, packages/js/CHANGELOG.md, packages/js/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> chore: run changeset version

apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncId.ts
Move multipeer test
- Move multipeer sync test
=> feat: Move multipeertest

apps/hubble/src/rpc/server/test/concurrency.test.ts, apps/hubble/src/rpc/server/test/submitService.test.ts
Concurrency and Submit service tests
- Concurrency and Submit service tests
=> feat: move concurrency and submit service tests

apps/hubble/src/network/p2p/connectionFilter.ts, apps/hubble/src/network/p2p/gossipNode.ts, apps/hubble/src/network/p2p/protocol.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/syncId.ts, apps/hubble/src/network/sync/trieNode.ts
Updates documentation to be easier to parse and to reflect the latest behavior of the code.
- Adds or updates documentation to several methods and classes
- Removes an instance of unnecessary error handling
=> refactor: improve documentation in networking and cleanup some error handling

apps/hubble/src/rpc/server/test/concurrency.test.ts, apps/hubble/src/storage/engine/seed.ts
Improve concurrency test
- Add ethsigner to util
- Make sure to find the right messages first
=> fix: Improve concurrency test

.changeset/perfect-cars-remain.md, apps/hubble/src/rpc/server/index.ts, apps/hubble/src/rpc/server/test/eventService.test.ts, packages/js/src/client.ts, packages/js/src/types.ts, packages/js/src/utils.ts, packages/protobufs/package.json, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/index.ts, packages/protobufs/src/schemas/rpc.proto, packages/utils/src/client.ts, yarn.lock
=> chore: port subscribe gRPC method and event streaming to protobufs

.changeset/fair-dodos-smoke.md, packages/js/package.json, packages/js/src/types.ts, packages/protobufs/package.json, yarn.lock
=> chore: remove unused dependencies from packages

.changeset/fair-dodos-smoke.md, .changeset/perfect-cars-remain.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/js/CHANGELOG.md, packages/js/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> chore: bump versions

apps/hubble/src/eth/ethEventsProvider.ts
=> fix: create id registry events with tx hash

Dockerfile
Make it a bit easier to get started by connecting to mainnet.
While here, shrink the size of our image further by squashing layers in a final stage of the build. This gets us down from ~612MB to ~530MB.
Add `--network 1` flag to the default command flags so we connect to mainnet.
=> fix: Set default network ID to mainnet

apps/hubble/src/cli.ts, apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/utils/p2p.ts
Small improvements to documentation: why we use try-catch in a few places, comments for complex methods
See above
=> docs: minor improvements

apps/hubble/package.json, yarn.lock
Upgrade commander to 10
See above, no breaking changes relevant to us
=> chore: upgrade commander to 10

apps/hubble/src/rpc/server/test/bulkService.test.ts
Move bulkService test to protobufs
Move bulkService test to protobufs
=> feat: bulkServiceTest to protos

apps/hubble/src/storage/stores/sequentialMergeStore.ts
=> feat: increase SequentialMergeStore timeout

apps/hubble/src/cli.ts, apps/hubble/src/console/console.ts
Console improvements to connect to prod hubs
- Allow connecting to IPs and DNS names
- Improve connection errors
=> feat: Console connections to prod hub

apps/hubble/src/rpc/server/test/bulkService.test.ts
Fixes #526
Fix a flaky test
Fix the flaky userdataadd test
=> fix: flaky test.

apps/hubble/src/rpc/server/test/bulkService.test.ts
Fix accidental checkin
Remove unnecessary timeout. 
=> fix: Fix accidental checkin

apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/syncEnginePerf.test.ts
Add additional checks when fetching syncids during sync
- Check if our node has more messages at prefix, don't sync if it does
- Check if hashes already match, skip if they do
- Check to see other node actually has messages before requesting them
=> fix: Add checks before fetching syncIDs during sync

apps/hubble/src/network/p2p/gossipNode.test.ts
Forgot to check in the gossip test in previous PR
- test
=> fix: gossip test

apps/hubble/README.md
Add instructions on how to upgrade libp2p
See above
=> docs: libp2p upgrade instructions

apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/hubble.ts, apps/hubble/src/utils/logger.ts
=> feat: improve hub logging

apps/hubble/src/console/genCommand.ts
Run the yarn console in batched mode. 
- Run the `gen` command in batches of 100. 
=> fix: Run the yarn console gen command batched

apps/hubble/src/hubble.ts
=> fix: use msg instead of message for logs

apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/network/p2p/gossipNode.test.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/utils/p2p.test.ts, apps/hubble/src/utils/p2p.ts
Improve multiaddr parsing and error messages
- Parse bootstrap addresses properly
- Better error messages
=> fix: Better multiaddr parsing

apps/hubble/src/hubble.ts
=> fix: changing log message key again

apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/periodicSyncJob.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/storage/engine/index.ts
Clean shutdown the hub
- RPC node is shutdown first
- Wait for existing syncs first
- Wait for Merkle Trie queue
=> fix: Clean shutdown for sync and merkle trie

.changeset/bright-grapes-flash.md, .changeset/eight-bats-leave.md, .changeset/silly-boats-cry.md, .changeset/slow-monkeys-serve.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/js/CHANGELOG.md, packages/js/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> chore: update changeset versions

apps/hubble/README.md
Fixes #563.
Added `../` to the relative path.
=> fix: relative path on hubble docs not resolving to contributing.md

apps/hubble/src/network/sync/syncEngine.ts
Make sync interruptable
- Make sync interruptable during stop()
=> fix: Make sync interruptable

packages/js/src/client.ts, packages/protobufs/README.md, packages/protobufs/docs/message.md, packages/protobufs/docs/rpc.md, packages/protobufs/src/schemas/message.proto
Documenting the protobufs and gRPC endpoints will make it easier for developers to work with Hubs
Adding Markdown files that contain documentation for both
=> feat: grpc api documentation

.changeset/silly-trees-tickle.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/js/CHANGELOG.md, packages/js/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> chore: bump package versions

apps/hubble/src/cli.ts
Allow reading the server identity from env variable, to allow for persistent identity on the prod server
- Read identity from env
=> feat: Allow reading server identity from environment

.changeset/silly-trees-tickle.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, package.json, packages/js/CHANGELOG.md, packages/js/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> chore: bump changeset versions

Dockerfile, apps/hubble/.config/hub.config.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/connectionFilter.ts, apps/hubble/src/network/p2p/gossipNode.ts
Add an allowlist for the prod hub to access control who can sync/gossip
- Add allowlist
- Logging improvements
=> feat: p2p allowlist

apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/syncEngine.ts
Fix issue where period syncs would fails after a while
- Store PeerID along with contact info for peers
=> fix: Sync stalls after a few hours because PeerID are not stored

.changeset/poor-bears-thank.md, apps/hubble/src/rpc/server/test/userDataService.test.ts, apps/hubble/src/storage/stores/userDataStore.test.ts, packages/protobufs/docs/message.md, packages/protobufs/src/generated/message.ts, packages/protobufs/src/schemas/message.proto, packages/utils/src/factories.ts, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
Remove location from the protocol until the feature is more spec'ed out.
* Remove location as UserData type
=> chore: remove location

apps/hubble/src/cli.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/rpc/server/index.ts
Handle errors during startup
- Handle and log errors during startup
- Teardown and exit if startup fails
=> fix: Handle startup errors gracefully

packages/js/README.md, packages/protobufs/docs/message.md
See title.
Update @farcaster/js README to contain a quick start to fetch messages and simplify the creation of messages. Remove unused types from protobuf documentation.
=> docs: make improvements to documentation

apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
Add a test where multiple signers are used
- Test to check sync fetches the right signers, if many signers exist
=> chore: Add multiple signer test for sync

packages/js/src/builders.ts, packages/js/src/types.ts, packages/utils/src/time.ts
Add hints for developers about what format different timestamp values are in.
- add TSDoc comments to places in the public API that deal with time
=> docs: add TSDoc annotations to time functions and properties

apps/hubble/src/rpc/server/test/rpcAuth.test.ts
Fix duplicate test db name
- Fix rpcAuth test db name
=> fix: Fix rpcAuth test db name

packages/js/README.md
I wanted to make the README.md more copy and pastable
I removed duplicate imports from the package/js/README.md
n/a
=> docs: update packages js readme

packages/js/README.md
=> fix doc to use pubkey instead of priv key

.changeset/eighty-items-serve.md, .changeset/rotten-lamps-serve.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/js/CHANGELOG.md, packages/js/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> chore: changeset version

apps/hubble/src/hubble.ts, apps/hubble/src/rpc/server/index.ts
=> chore: force shutdown when stopping grpc server

package.json, yarn.lock
Upgrade dev dependencies in the monorepo to latest versions. 
See above.
=> chore: upgrade minor and patch versions of monorepo dependencies

.changeset/dirty-weeks-watch.md, .changeset/long-moles-buy.md, .changeset/real-bananas-grin.md, .changeset/twenty-eggs-perform.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
Bumping changeset versions for a release.
See above.
=> chore: changeset version bumps

packages/hub-nodejs/docs/Builders.md, packages/hub-nodejs/docs/Messages.md, packages/hub-nodejs/docs/README.md, packages/hub-nodejs/docs/Utils.md, packages/hub-nodejs/examples/write-signer.md, packages/protobufs/docs/message.md
Fleshing out documentation for hub-nodejs package.
- Add docs for Utils
- Add docs for Verification messages and methods
- Fix numerous small issues
=> docs(hub-nodejs): improve docs based on feedback

apps/hubble/src/storage/engine/index.test.ts, apps/hubble/src/storage/engine/index.ts
Make error messages from engine more descriptive.
=> chore: improve engine error messages

packages/hub-nodejs/README.md, packages/hub-nodejs/docs/Builders.md, packages/hub-nodejs/docs/Client.md, packages/hub-nodejs/docs/README.md
Increases documentation coverage for our library
- Add documentation to explain pagination
- Add more clarity to the responses that Client methods return
- Clean up other minor issues. 
No changeset needed for a documentation change.
=> docs(hub-nodejs): add documentation for pagination, responses

packages/hub-nodejs/README.md
Typo. The contributing guideline link is 404.
=> docs: typo fix contributing.md 404

.changeset/ten-buttons-confess.md, apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts, apps/hubble/src/storage/db/rocksdb.ts
Exit a hub if a newer hub startsup with the same RocksDB
- Write a pid.txt file with the current PID
- If this file gets overwritten, exit the current hub, yielding to the newer hub
=> feat: Exit if superseeded by a newer hub

apps/hubble/src/hubble.ts
Fix accidentally removed sleep() from prev commit
=> fix: Fix accidentally removed sleep from prev commit

packages/hub-nodejs/docs/Client.md
Increase documentation coverage for Client methods.
See title.
Changeset not needed for documentation changes.
=> docs: add documentation for userdata, verifications and streaming services

.changeset/afraid-adults-travel.md, apps/hubble/src/rpc/server.ts, apps/hubble/src/storage/db/message.ts, apps/hubble/src/storage/stores/castStore.ts, apps/hubble/src/storage/stores/reactionStore.ts, apps/hubble/src/storage/stores/signerStore.test.ts, apps/hubble/src/storage/stores/signerStore.ts, apps/hubble/src/storage/stores/types.ts, packages/protobufs/src/generated/gossip.ts, packages/protobufs/src/generated/hub_event.ts, packages/protobufs/src/generated/hub_state.ts, packages/protobufs/src/generated/id_registry_event.ts, packages/protobufs/src/generated/job.ts, packages/protobufs/src/generated/message.ts, packages/protobufs/src/generated/name_registry_event.ts, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/generated/sync_trie.ts, packages/protobufs/src/schemas/rpc.proto
Closes https://github.com/farcasterxyz/hubble/issues/693
* List methods accept `reverse` param to reverse ordering
=> feat: add reverse rpc pageOption

packages/hub-nodejs/README.md, packages/hub-nodejs/docs/Builders.md, packages/hub-nodejs/docs/Utils.md, packages/hub-nodejs/docs/signers/EthersEip712Signer.md, packages/hub-nodejs/docs/signers/NobleEd25519Signer.md
See title
See title
No changeset needed for a docs update
=> docs(hub-nodejs): update invocations to match 0.5.0 release, fix minor typos

apps/hubble/src/hubble.ts
=> chore: use warn rather than error for submit* logs

apps/hubble/src/storage/engine/index.ts, apps/hubble/src/storage/jobs/pruneMessagesJob.ts, apps/hubble/src/storage/stores/castStore.test.ts, apps/hubble/src/storage/stores/castStore.ts, apps/hubble/src/storage/stores/reactionStore.test.ts, apps/hubble/src/storage/stores/reactionStore.ts, apps/hubble/src/storage/stores/signerStore.test.ts, apps/hubble/src/storage/stores/signerStore.ts, apps/hubble/src/storage/stores/storeEventHandler.test.ts, apps/hubble/src/storage/stores/storeEventHandler.ts, apps/hubble/src/storage/stores/userDataStore.test.ts, apps/hubble/src/storage/stores/userDataStore.ts, apps/hubble/src/storage/stores/verificationStore.test.ts, apps/hubble/src/storage/stores/verificationStore.ts, apps/hubble/src/test/bench/syncEngine.ts
=> chore: minor pruning refactor

apps/hubble/src/storage/engine/index.ts
=> feat: move signer pruning before other sets

apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/console/console.ts, apps/hubble/src/rpc/adminServer.ts
Change port numbers in the code to 2282 (gossip), 2283 (rpc), 2284 (adminRPC)
=> chore: Change port numbers

apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/periodicSyncJob.ts, apps/hubble/src/network/sync/syncEngine.ts
Improve logging during sync/gossip
=> chore: better logging

apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/syncEngine.ts
When merging messages with gossip, don't attempt to use RPC connections. 
- Merge gossip messages without RPC connections
- If a gossip message fails if it's dependent signer is not yet available, sync will retry it 
=> fix: Don't use RPC while handling gossip messages

packages/hub-nodejs/docs/Utils.md
Fixes #735. See: https://github.com/vinliao/hubble/blob/nodejs-docs/packages/hub-nodejs/docs/Utils.md
Add examples and the tables for each function in `utils.md`
=> docs(hub-nodejs): add docs for utils.md

Dockerfile
We want to be able to collect runtime metrics.
Update the `Dockerfile` to include a required package. While here, also update the exposed ports since we've changed the defaults.
=> chore: Include package to enable Node.js runtime metrics collection

apps/hubble/src/hubble.ts
Catch exceptions while connecting to RPC
- try catch exceptions while opening RPC clients
=> fix: Catch any SSL errors if peer unexpectedly dies

apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/periodicSyncJob.ts, apps/hubble/src/rpc/server.ts
Handle exceptions when peer unexpectedly dies or disconnects.
Handle errors in various places.
=> fix: Handle errors when peer unexpectedly disconnects

.changeset/healthy-poems-compare.md, .changeset/hungry-nails-collect.md, .changeset/shaggy-hairs-tap.md, .changeset/spicy-ants-sin.md, .changeset/tame-avocados-develop.md, .changeset/ten-ducks-roll.md, .changeset/wise-peaches-remain.md, .changeset/wise-sloths-tan.md, .changeset/witty-trainers-bake.md, .changeset/yellow-islands-join.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/eslint-config-custom/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json, packages/prettier-config-custom/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
=> chore: changeset version and make custom dev packages private

apps/hubble/src/console/console.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/trieNode.ts, apps/hubble/src/rpc/server.ts
Improve logging for sync errors
Improve logging for sync errors
=> chore: improve logging for failure cases

apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/trieNode.ts, apps/hubble/src/rpc/server.ts, apps/hubble/src/utils/periodicTestDataJob.ts
Submit test data via the RPC, so the newly added messages also get gossip'd
- Add test data via RPC
=> fix: Test data messages should be gossiped

.changeset/chilly-bats-kneel.md, .changeset/eight-fans-move.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
Preparing for the first testnet release.
Release a new version of hub-nodejs client since the interfaces have been changed and tag a version for testnet release.
=> chore: release new version of packages

packages/hub-nodejs/README.md, packages/hub-nodejs/docs/Client.md
Preparing for testnet launch
Update documentation to point to testnet hubs in examples.
No changeset for docs PRs
=> docs(hub-nodejs): point urls to testnet hubs

CONTRIBUTING.md
Fix typo in CONTRIBUTING.md
Fix typo in CONTRIBUTING.md
=> chore: fix typo in contributing.md

apps/hubble/README.md
See title
- Update README to reflect new instructions
No changeset needed for docs PRs
=> docs(hubble): update instructions for connecting to testnet

apps/hubble/src/utils/periodicTestDataJob.ts
Fix a small issue in the previous PR
- Use keys() properly
=> fix: Missed a check if previous PR

apps/hubble/src/hubble.ts, apps/hubble/src/storage/jobs/checkFarcasterVersionJob.ts, apps/hubble/src/utils/versions.ts
Closes #131 
* See this doc for protocol schedules: https://warpcast.notion.site/Versioning-Upgrades-Public-10b90077591247788d11e69f54f6a67c
* Shuts hub down if no min version available
=> feat: expire hubs

apps/hubble/src/hubble.ts, apps/hubble/src/storage/engine/index.ts, apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
=> feat: add validate or revoke messages cleanup job

codecov.yml
ignore generated code in codecov
ignore generated code in codecov
=> chore: set codecov to ignore generated files

codecov.yml
fix codecov.yml
fix codecov.yml
=> chore: fix codecov.yml

.changeset/beige-lemons-float.md, apps/hubble/src/cli.ts
Better error when id protobuf is not found
- Show how to create id if protobuf not found.
=> fix: Better error when id protobuf is not found

Dockerfile
Copy the hub-nodejs into Dockerfile
Copy the hub-nodejs into Dockerfile
=> fix: Copy hub-nodejs dir into docker

.changeset/gold-pots-double.md, packages/core/tsup.config.ts, packages/hub-nodejs/package.json, packages/hub-nodejs/tsup.config.ts, packages/hub-web/package.json, packages/hub-web/tsup.config.ts
=> chore: update tsup configs

apps/hubble/src/storage/jobs/gossipContactInfoJob.test.ts, apps/hubble/src/storage/jobs/gossipContactInfoJob.ts
Fix merge conflict between https://github.com/farcasterxyz/hub-monorepo/pull/817 and  https://github.com/farcasterxyz/hub-monorepo/pull/818 and 
Fix imports to use the new package
=> fix: Fix build due to merge conflict with main

.changeset/forty-drinks-battle.md, .changeset/three-zoos-train.md, packages/hub-web/README.md, packages/hub-web/src/client.ts
export getAuthMetadata & getHubRpcClient for hub-web
export getAuthMetadata & getHubRpcClient for hub-web
=> chore: export getAuthMetadata & getHubRpcClient

apps/hubble/src/rpc/server.ts
Log cases where the subscribe() stream is not being consumed by the client and it causes a lot of memory increase. We should monitor this and destroy() the stream if it is happening in prod. 
- Add extra logging if RSS increases by too much. 
=> fix: Log cases where the subscribe stream is not being consumed

.changeset/stale-berries-fold.md, packages/hub-web/src/client.ts
fiix error code for no connection
fiix error code for no connection
=> chore: fiix error code for no connection

.changeset/twenty-beans-draw.md, packages/hub-web/src/client.ts
add grpc error code as fallback
add grpc error code as fallback
=> fix: add grpc error code as fallback

.changeset/eighty-buckets-shout.md, .changeset/light-gifts-remember.md, .changeset/stale-berries-fold.md, .changeset/twenty-beans-draw.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json, packages/hub-web/CHANGELOG.md, packages/hub-web/package.json
=> chore: run changeset version (apr 6 2023)

README.md
=> docs: minor fix to root readme

package.json, turbo.json, yarn.lock
=> chore: upgrade turbo and add protoc command

apps/hubble/src/rpc/server.ts
If clients are stalled, don't just log the error. Kill the stream. 
Kill stream if clients are not consuming it.
=> Killstream

.changeset/breezy-ducks-admire.md, packages/hub-web/CHANGELOG.md, packages/hub-web/package.json
=> chore: changeset version and publish @farcaster/hub-web

apps/hubble/src/allowedPeers.mainnet.ts
=> chore: add peer ids for trusted mainnet hubs from users

.github/workflows/release-packages.yml, package.json
=> add release-packages workflow

.github/workflows/release-packages.yml
=> fix: add on to release-packages workflow

packages/hub-nodejs/docs/Utils.md
Small patch to fill the TODOs in `Utils.md`. All description was taken from `src/errors.ts`.
=> docs: add error code in Utils.md

apps/hubble/src/allowedPeers.mainnet.ts
So I can run my mainnet node
Add my peer id to maininet allowlist
=> chore: Add mainnet peer for sanjay

.changeset/few-kids-suffer.md, .changeset/modern-houses-matter.md, .changeset/nervous-bats-help.md, .changeset/spotty-dryers-kneel.md, .changeset/tiny-pots-collect.md, .changeset/wicked-planets-walk.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json
=> chore: changeset version hubble v1.1.0

.github/workflows/release-hubble.yml, .github/workflows/release.yml
=> chore: add release.yml github action

.github/workflows/release.yml, package.json
=> add release-all script

.github/PULL_REQUEST_TEMPLATE.md
=> chore: add checklist item to sign commits

apps/hubble/src/allowedPeers.mainnet.ts
New peer, will be managed by bitwise engineering team: @molo, @pal, @noun40
A new peer ID was added.
=> chore: add new mainnet peer for molo

apps/hubble/src/utils/versions.test.ts
Alerts us in case we're falling behind on releasing a new version
=> chore: fail the build if current version is too close to expiry

apps/hubble/src/allowedPeers.mainnet.ts
Adding a mainnet peer on behalf of Neynar
Adds the peer id (steps [here](https://warpcast.notion.site/warpcast/Mainnet-Hubs-dc2ff6d528f64992afe03797b61dec32))
NA
=> chore: add a peer for @neynar

apps/hubble/src/allowedPeers.mainnet.ts
New peer managed by https://github.com/NaturalSelectionLabs
Adding a new peer
=> chore: add new mainnet peer for rss3

apps/hubble/src/allowedPeers.mainnet.ts
New peer managed by https://github.com/cryptobenkei
Adding a new peer
=> chore: Add mainnet peer to allowed peers

apps/hubble/src/cli.ts
=> fix: parse cli chunk-size as number

apps/hubble/src/rpc/server.ts
=> chore: log when stream starts

packages/hub-nodejs/examples/chron-feed/README.md, packages/hub-nodejs/examples/write-data/README.md, packages/hub-nodejs/examples/write-data/index.ts, packages/hub-nodejs/examples/write-data/package.json, packages/hub-nodejs/examples/write-data/yarn.lock
Update write-data example to use the latest packages and have clearer instructions
- Improved README instructions
- Added commented instructions for authd vs unauthed hubs
- Upgraded hub-nodejs to 0.7.0
=> chore(hub-nodejs): update write-data example

apps/hubble/src/allowedPeers.mainnet.ts
=> chore: add @les to allowlist

CONTRIBUTING.md, packages/hub-nodejs/docs/Builders.md, packages/hub-nodejs/docs/Utils.md
=> chore: fix typos in documentation

apps/hubble/src/allowedPeers.mainnet.ts
Adding peer ids that users have requested
Adding peer ids that users have requested
=> chore: add peerids for razzle, pseudobun

.changeset/angry-lizards-hammer.md, .changeset/early-swans-clean.md, .changeset/fast-olives-promise.md, .changeset/flat-trainers-hide.md, .changeset/forty-onions-grin.md, .changeset/perfect-baboons-visit.md, .changeset/plenty-trainers-raise.md, .changeset/rotten-keys-smell.md, .changeset/six-eyes-drive.md, .changeset/tidy-roses-crash.md, .changeset/twenty-chairs-switch.md, .changeset/violet-radios-beam.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json, packages/hub-web/CHANGELOG.md, packages/hub-web/package.json
=> chore: Release 1.3.4

.changeset/tidy-needles-greet.md, apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts, apps/hubble/src/storage/stores/store.ts
Prepare for mainnet migration by deprecating time based pruning early. 
=> feat: deprecate time based pruning

scripts/replicator.sh
The other tag doesn't seem to work with GitHub's URL scheme, so switch to one similar to what we did with Hubble.
=> chore: Update replicator script

.changeset/brave-dancers-cover.md, .changeset/five-olives-drum.md, .changeset/orange-crabs-double.md, .changeset/orange-rabbits-join.md, .changeset/sharp-students-explode.md, .changeset/smooth-berries-mate.md, .changeset/tame-spies-rule.md, .changeset/thirty-seals-laugh.md, .changeset/tidy-dolphins-repeat.md, .changeset/unlucky-toes-bake.md, .changeset/wild-tigers-beam.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json, packages/hub-web/CHANGELOG.md, packages/hub-web/package.json
=> chore: Release 1.6.1

.changeset/nice-bulldogs-return.md, packages/core/CHANGELOG.md, packages/core/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json, packages/hub-web/CHANGELOG.md, packages/hub-web/package.json
Release new core and hub-nodejs package versions
=> chore: Release new package version

apps/hubble/www/docs/intro/install.md, apps/hubble/www/docs/intro/monitoring.md
I just went through setting up a node and updated the docs to hopefully mitigate some hiccups I ran into for anybody that does this in the future. 
Updating the hub installation and monitoring docs. 
=> docs: updated install and monitoring pages

.changeset/honest-flies-jog.md, .changeset/wicked-masks-study.md, .changeset/yellow-chefs-dance.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/core/CHANGELOG.md, packages/core/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json
=> chore: Release 1.13.3

apps/hubble/src/network/sync/syncHealthJob.ts, apps/hubble/src/utils/syncHealth.ts
We need the message hash to understand the "message already merged errors". Would be useful to search for the hash to understand when the message got merged initially. 
=> chore: add message hash to sync health errors

.changeset/flat-beers-help.md, packages/core/CHANGELOG.md, packages/core/package.json, packages/hub-nodejs/CHANGELOG.md, packages/hub-nodejs/package.json
=> chore: Release `@farcaster/core@0.16.4` and `@farcaster/hub-nodejs@0.13.5`
