package.json, src/engine.ts, src/simulation.ts
The simulator incorrectly set rootBlockHash to 0x0, which is the symbol we use in prevRootBlockHash to indicate that we do not want chaining to happen. However, because the strings matched, the check actually passed and allowed the blocks to be chained together. 
The right fix is to ensure that each rootBlockHash is a valid ethereum blockhash, which won't be implemented until a later phase, so we are adding a quick validation to prevent these errors from being accidentally introduced.
=> fix: do not allow root blockHash to be set to 0x0

src/client.ts, src/debugger.ts, src/engine.test.ts, src/engine.ts, src/factories.ts, src/node.ts, src/simulation.ts
The Engine now keeps track of simulated "Signer Change" events from the Farcaster Registry. From now on,  Roots - and by extension, Casts - will only be accepted if the signer address owned the username at the block specified in the Root.
=> feat: engine tracks signers for usernames

src/client.ts, src/debugger.ts, src/farcasterNode.ts, src/node.ts, src/simulation.ts, src/simulator/basicSimulator.ts, src/simulator/chaosSimulator.ts, src/simulator/index.ts
This change defines a simulator model that makes it easy to write multiple scenarios to test different behaviors. It also implements two types of scenarios: 
1. Basic Scenario - where users broadcast messages in sequence to nodes that sync regularly
2. Chaos Scenario - where users broadcast messages in random order to nodes that sync irregularly
=> Scenario Simulators

src/debugger.ts, src/simulation.ts, src/simulator/chaosSimulator.ts, src/simulator/index.ts, src/simulator/splitBrainAltSimulator.ts, src/simulator/splitBrainSimulator.ts
We add two new scenarios that model network partitions: 
1. SplitBrain - clients send messages to one side of a partition, which is later healed
2. SplitBrainAlt - clients alternate sending messages to different sides of the partition, which is later healed
=> Scenario Simulators: Split Brain

src/client.ts, src/debugger.ts, src/engine/engine.cast.test.ts, src/engine/index.ts, src/factories.ts, src/sets/castSet.test.ts, src/sets/castSet.ts, src/simulator/basicSimulator.ts, src/simulator/chaosSimulator.ts, src/simulator/splitBrainAltSimulator.ts, src/simulator/splitBrainSimulator.ts, src/types/index.ts, src/types/typeguards.ts
Right now the codebase is inconsistent in terms of naming remove sets and remove messages:
* Casts use `CastDelete` and a `_deletes` set
* Verifications (and soon signers) use `VerificationRemove`, `SignerRemove`, and a `_removes` set
This PR renames `CastDelete` to `CastRemove` and `CastSet._deletes` to `CastSet._removes` to be consistent. In CRDT literature, "remove set" is more common than "delete set."
=> Rename CastDelete to CastRemove

src/client.ts, src/engine/engine.verification.test.ts, src/engine/index.ts, src/factories.ts, src/sets/verificationSet.ts, src/types/index.ts, src/types/typeguards.ts
Renaming `externalAddressUri` to `externalUri` for verifications. See [conversation here](https://github.com/farcasterxyz/protocol/pull/16#discussion_r928197826) for background on the change.
=> Rename externalAddressUri to externalUri

src/client.ts, src/engine/engine.cast.test.ts, src/engine/engine.reaction.test.ts, src/engine/engine.root.test.ts, src/engine/engine.verification.test.ts, src/engine/index.ts, src/factories.ts, src/simulation.ts, src/simulator/basicSimulator.ts, src/simulator/chaosSimulator.ts, src/simulator/splitBrainAltSimulator.ts, src/simulator/splitBrainSimulator.ts, src/types/index.ts, src/utils.test.ts, src/utils.ts
Implements https://github.com/farcasterxyz/hub/issues/49
Summary of changes:
* Add `SignatureAlgorithm` enum type
* Add `MessageSigner` type that encompasses either an Ed25519 signer (with private key) or Ethereum signer (with wallet)
* Use `MessageSigner` instead of `privateKey` in factories and whenever we generated a key pair in order to support multiple types of signers
* Add `generateEd25519Signer` and `generateEthereumSigner` utils
* Clean up factories to share envelope stamping/signing code
* Update `validateMessage` method in the engine to handle multiple kinds of signatures
=> Add signatureType to messages

.github/workflows/ci.yml, .gitignore, package.json
adding ci reports to make it easier to determine if a method has sufficient coverage when reviewing ode.
=> ci: upload coverage results to codecov

CONTRIBUTING.md
Adds details about signing, which most people don't realize they have to do before making a PR
_Choose one of the options below by adding an `x` now or at any time before submitting for review_
=> docs: add signing instructions to CONTRIBUTING

src/client.ts, src/engine/engine.verification.test.ts, src/engine/index.ts, src/factories.ts, src/types/index.ts, src/types/typeguards.ts
Last item from https://github.com/farcasterxyz/hub/issues/49
Replace `eip-191-0x45` string with `SignatureAlgorithm.EthereumPersonalSign` for `externalSignatureType` field of verifications.
=> chore: use SignatureAlgorithm.EthereumPersonalSign for verification's externalSignatureType attribute

.github/PULL_REQUEST_TEMPLATE.md
The PR template is heavy-handed, and it causes Github to think that the change type list is a todo list in the PR list view.
_Choose one of the options below by adding an `x` now or at any time before submitting for review_
Ask contributors to use github labels to mark PRs with the change type instead of a checklist.
=> docs: simplify PR template to use github labels for change type

src/client.test.ts, src/client.ts, src/engine/engine.follow.test.ts, src/engine/engine.revoke.test.ts, src/engine/index.ts, src/factories.ts, src/sets/followSet.test.ts, src/sets/followSet.ts, src/types/index.ts, src/types/typeguards.ts
Implements https://github.com/farcasterxyz/hub/issues/60
Tracks follows using a LWW set and similar message format to reactions. Integrated follow set into engine and client.
* Conflicts are resolved using a very similar mechanism to the reactions set, except if two follows with the same timestamp conflict, the unfollow wins, and we only check message hash if the two messages have the same `active` value (i.e. both follows or both unfollows)
* While follows are very similar to reactions, I chose to implement them separately because the target will be different (reactions are attached to casts, and follows are attached to users) and reactions have a type whereas follows do not. Also, reactions as they're implemented now allow only one reaction per target, so putting both actions in the …
=> feat: follow set

src/client.test.ts
Faker got imported twice into `client.test.ts` due to merged code and is causing tests to fail.
Remove import
=> bugfix: Faker imported twice in client.test.ts

src/engine/engine.verification.test.ts, src/engine/index.ts, src/factories.ts
Valid Ethereum addresses can be represented in lowercase, checksummed, or uppercase form. Hubs should accept verification messages that use any format, as long as the verification claims associated with those messages used the same format. Thanks @gsgalloway for the catch on this.
Updated engine and factories to allow lowercase, checksummed, or uppercase addresses.
=> feat: allow checksummed, lowercased, or uppercased externalUri for verifications

src/engine/engine.cast.test.ts, src/engine/engine.follow.test.ts, src/engine/engine.reaction.test.ts, src/engine/engine.revoke.test.ts, src/engine/engine.signer.test.ts, src/engine/engine.verification.test.ts, src/engine/index.ts
A generic merge handler moves the message parsing burden entirely into the engine
Added a generic `mergeMessage` api to the Engine that figures out which inner `merge` function to call based on the message type.
=> feat: add a generic merge handler for the engine

package.json, src/network/rpc.ts, yarn.lock
* Bump node version to most recent LTS (16.17.0) and upgrade packages
* Remove console.log in rpc.ts file to clean up test suite output
=> chore: bump node version and upgrade packages

src/engine/index.ts, src/network/rpc.sync.test.ts, src/network/rpc.test.ts, src/network/rpc.ts, src/network/rpcSync.test.ts
Fixes https://github.com/farcasterxyz/hub/issues/102
- Wrote a simple test that copies data from one Engine (server) to another (client) over RPC.
- Added RPC APIs for querying IDRegistry events as well
Depends on https://github.com/farcasterxyz/hub/pull/105. 
I will rebase this once that's landed.
=> feat(sync): Implement a simple Engine sync over RPC

package.json, yarn.lock
Upgrading jest, ts-jest to see if latest fixes resolve issues with importing libp2p
See above
=> chore: upgrade jest and related packages to latest

.github/workflows/ci.yml
Add yarn audit so that ci fails when a vulnerability is found in a package we own.
N/A
=> ci: add yarn audit

codecov.yml
Codecov complains if total repo coverage decreases by any amount, which creates a lot of false positives. Eliminating false positives by using a hardcoded threshold lets us to focus on the important failures (patch changes that reduce coverage). Also, reviewers should always be thoughtful about inspecting coverage reports to determine if a change is sufficiently covered. 
Add 85% requirement to the codecov project, instead of using auto
=> ci: should not fail on every project coverage decrease

nodemon.json, package.json, src/server.ts, yarn.lock
Create an executable file that can be used to start the Hub server
Use [esbuild-kit/tsx](https://github.com/esbuild-kit/tsx) to handle compilation of TypeScript and ESM modules. This was 70% faster than using the previous ts-node configuration. 
=> chore: create executeable entrypoint (server.ts) using tsx

jest.config.ts, package.json
Fixes #141 
`jest.config.ts` was using a combination of manual and pre-set configuration and was being exported as a different type. Restoring settings to [recommended configuration](https://kulshekhar.github.io/ts-jest/docs/next/guides/esm-support/) seemed to resolve the issue
=> test: fix yarn jest failing on node.test.ts

src/engine/index.ts, src/sets/castSet.test.ts, src/sets/castSet.ts
CastSet implemented LWW-RW instead of RW-LWW which meant that a remove message would be ignored if it was incorrectly generated with an older timestamp. 
This PR fixes the core issue by making the RemoveWins rule take precedence over the LastWriteWins rule. It also:
1. Adds more class and method documentation
2. Renames  CastSet's `getAllCastMessagesByUser` to `getAllCastsByUser` to be consistent with other methods
3. Improves test coverage for some lines and cases  
=> fix(CastSet): remove-wins should trump last-write-wins

.github/workflows/ci.yml, package.json
Upgrading Node to the latest, stable, current version to bring it in sync with other Farcaster repos
Upgrade node version from 16.17 to 18.7
=> chore: upgrade node to v18.7.0 to sync with other farcaster repos

package.json, src/bench.ts, src/engine/mock.ts, src/hub.ts, src/network/node.test.ts, src/network/node.ts, src/network/rpc.ts, src/server.ts, src/types/typeguards.ts, tsconfig.json
We want to be able to test a "real" network of hubs with dummy data
Added a benchmark script that can generate data for `N` users and broadcast 1 `castShort` for each to the network. 
This is just the first pass at the bench client. We'll presumably need more features and changes over time.
=> feat: Script to benchmark a network of Hubs

package.json, src/network/rpc/index.ts
After the previous #149, `yarn start` was broken with the following error: 
```
SyntaxError: The requested module './interfaces' does not provide an export named 'RPCHandler'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
at async Promise.all (index 0)
at async ESMLoader.import (node:internal/modules/esm/loader:541:24)
at async loadESM (node:internal/process/esm_loader:91:5)
at async handleMainPromise (node:internal/modules/run_main:65:12)
```
Also `yarn dev` and `yarn bench` were broken since they didn't point to the newly refactored file names.
The core issue is that node --experimental-modules has bad support for named exports, and seems to always fail on exporting a named interface. The hacky …
=> fix: broken package.json commands, broken named imports due to node --experimental-modules

src/cli.ts, src/hub.ts, src/network/p2p/node.ts, src/storage/engine/engine.mock.test.ts
Hub operators need to know exactly which ports to make externally reachable. 
Just like RPC, the libp2p listen port also needs to be configurable.
Add an option to configure which port libp2p binds to
=> fix: allow configuration of libp2p listen port

.gitignore, package.json, src/cli.ts, src/hub.ts, src/network/p2p/node.ts
Hubs use libp2p PeerIds to identify each other. Currently Hubs just generate a new keypair and corresponding PeerId every time they are started up. 
This means it's not possible to enforce which Hubs are allowed to participate in a network. 
By persisting PeerIds we ensure that Hubs always use the same identity to participate on the p2p network
- Add a command to generate a new peerId file
- Add a command to verify an existing peerId file
- Add a command to pass in a peerId file to a Hub
fixes https://github.com/farcasterxyz/hub/issues/156
=> feat: add support for persistent peerIds

.config/hub.config.ts, .eslintrc.cjs, .gitignore, .hub/start.config.ts, src/cli.ts
Too many knobs to control via cli. A config file lets us define defaults. 
Add the option to specify a config file to use to start a Hub.
Also, removed `Commander` option defaults as there's no way to differentiate between user specified options and `Commander` defaults in an `action` handler.
=> Hub config file

src/hub.ts, src/network/p2p/protocol.test.ts, src/network/p2p/protocol.ts, src/network/rpc/client.ts, src/network/rpc/interfaces.ts, src/network/rpc/rpc.test.ts, src/network/rpc/server.ts, src/storage/db/signer.ts, src/storage/engine/engine.cast.test.ts, src/storage/engine/engine.follow.test.ts, src/storage/engine/engine.reaction.test.ts, src/storage/engine/engine.revoke.test.ts, src/storage/engine/engine.signer.test.ts, src/storage/engine/engine.verification.test.ts, src/storage/engine/index.ts, src/storage/engine/mock.ts, src/storage/provider/abis.ts, src/storage/provider/idRegistryProvider.ts, src/storage/sets/signerSet.test.ts, src/storage/sets/signerSet.ts, src/test/e2e/hub.test.ts, src/test/e2e/rpcSync.test.ts, src/test/factories.ts, src/test/perf/bench.ts, src/types/index.ts, src/types/typeguards.ts
Hub was not using strict camel casing for naming, while protocol was (IDRegistry vs IdRegistry)
All instances of IDRegistry are now IdRegistry
=> refactor: IDRegistry to IdRegistry to align with protocol naming

.config/hub.config.ts, src/cli.ts, src/hub.ts, src/network/p2p/node.test.ts, src/network/p2p/node.ts, src/test/perf/bench.ts, src/utils/p2p.test.ts, src/utils/p2p.ts
- Added the `--ip` option to Hub. IP addresses can be specified as regular strings now instead of multiaddrs
- Removed the `--multiaddr` option from Hub. 
=> chore: use IP address strings to specify hub address

src/cli.ts, src/hub.ts, src/network/p2p/node.ts, src/network/rpc/client.ts, src/network/rpc/rpc.test.ts, src/network/rpc/server.ts, src/test/perf/bench.ts, src/test/perf/playback.ts, src/test/perf/scenario.ts, src/test/perf/setup.ts, src/test/perf/utils.ts, src/test/perf/verify.ts, src/utils/p2p.test.ts, src/utils/p2p.ts
This is what it looks like now.. 
```
$ yarn bench -l "/ip6/::/tcp/57949" "/ip6/::/tcp/57952"
{"level":30,"time":1666371935295,"pid":27736,"hostname":"MacBook-Pro","msg":"Generating IdRegistry events for 10 users."}
{"level":30,"time":1666371935887,"pid":27736,"hostname":"MacBook-Pro","time":"0.591","msg":"Generated 10 users. UserInfo has 10 items"}
{"level":30,"time":1666371935941,"pid":27736,"hostname":"MacBook-Pro","time":"0.054","msg":"IdRegistry Events submitted"}
{"level":30,"time":1666371935941,"pid":27736,"hostname":"MacBook-Pro","msg":"10 events submitted successfully. 0 events failed."}
{"level":30,"time":1666371935941,"pid":27736,"hostname":"MacBook-Pro","msg":"_Waiting a few seconds for the network to synchronize_"}
{"level":30,"time":1666371946125,"pid":27736,"hostname":"MacBo …
```
=> fix: rewrite perf test

src/storage/flatbuffers/model.ts, src/storage/flatbuffers/typeguards.ts, src/storage/flatbuffers/types.ts, src/storage/sets/flatbuffers/castSet.ts, src/storage/sets/flatbuffers/followSet.test.ts, src/storage/sets/flatbuffers/followSet.ts, src/test/factories/flatbuffer.ts
Continuing to migrate sets over to flatbuffers. Original flatbuffers PR here: https://github.com/farcasterxyz/hub/pull/181
* Add FollowSet version that uses flatbuffers
* Add FollowAddModel and FollowRemoveModel wrappers
* Index follows by user ID
* Add follow-related types to flatbuffers factories
=> feat: add flatbuffer followset

package.json, src/network/rpc/rpc.test.ts, src/network/sync/syncEngine.test.ts, src/storage/db/binaryrocksdb.test.ts, src/storage/db/cast.test.ts, src/storage/db/message.test.ts, src/storage/db/rocksdb.test.ts, src/storage/engine/engine.cast.test.ts, src/storage/engine/engine.follow.test.ts, src/storage/engine/engine.mock.test.ts, src/storage/engine/engine.reaction.test.ts, src/storage/engine/engine.revoke.test.ts, src/storage/engine/engine.signer.test.ts, src/storage/engine/engine.verification.test.ts, src/storage/engine/mock.ts, src/storage/sets/castSet.test.ts, src/storage/sets/followSet.test.ts, src/storage/sets/reactionSet.test.ts, src/storage/sets/signerSet.test.ts, src/storage/sets/verificationSet.test.ts, src/test/e2e/hub.test.ts, src/test/factories.ts, src/test/factories/flatbuffer.ts, src/test/perf/setup.ts, src/utils/crypto.test.ts, yarn.lock
`faker` is a deprecated npm module that may be also responsible for other issues with deploys, so we're replacing with `faker-js` which is a more maintained implementation
- `faker` was swapped in place for `faker-js` which mostly just worked with some API changes. 
- `signedAt` for some messages had to be explicitly set since `faker.date.recent().getTime()` works different from `faker.time.recent()`
=> chore: replace faker with faker-js

.yarnrc, yarn.lock
Dockerfile builds are failing on GH actions due to timeouts when talking to the yarn registry
Switch the registry from yarn to npm to debug if that is the cause
=> fix: debug deploy failures by switching to npm registry

tsconfig.json
`ts-jest` constantly fails when commenting out tests because it leaves unused locals, slowing down the pace of iteration when writing tests
`noUnusedLocals` is not enforced in ts-config as a hard failure and is instead enforced as an eslint warning (no-unused-vars)
=> chore: disable noUnusedLocals in tsconfig

src/storage/flatbuffers/messageModel.test.ts, src/storage/flatbuffers/messageModel.ts, src/storage/sets/flatbuffers/castSet.test.ts, src/storage/sets/flatbuffers/castSet.ts, src/storage/sets/flatbuffers/followSet.test.ts, src/storage/sets/flatbuffers/followSet.ts, src/storage/sets/flatbuffers/reactionSet.test.ts, src/storage/sets/flatbuffers/reactionSet.ts, src/storage/sets/flatbuffers/signerSet.test.ts, src/storage/sets/flatbuffers/signerSet.ts, src/storage/sets/flatbuffers/verificationSet.test.ts, src/storage/sets/flatbuffers/verificationSet.ts, src/test/factories/flatbuffer.ts
Variables names for certain constructs (e.g. `reactionRemoveTimestampHash`) were becoming verbose and using `TsHash` instead of `TimestampHash` avoids a lot of unnecessary density. 
All instances of timestampHash were changed to tsHash, and some incorrectly named instances of hash were renamed to tsHash
=> refactor: rename timestampHash to tsHash

src/storage/sets/flatbuffers/reactionSet.test.ts, src/storage/sets/flatbuffers/reactionSet.ts
Our merge logic of comparing the timestamp hashes before comparing message types can lead to unexpected behaviors for users.  If a user created a Like, and then removed it within the same second, there is a 50% chance that the remove will be discarded. 
When merging, compare timestamps, then message types and finally hashes to resolve ties.
=> fix: reaction merge should use lww-rw-hash comparisons to avoid unexpected user behavior

src/storage/db/cast.ts, src/storage/db/follow.ts, src/storage/db/signer.ts, src/storage/db/verification.ts, src/storage/sets/flatbuffers/castStore.test.ts, src/storage/sets/flatbuffers/castStore.ts, src/storage/sets/flatbuffers/followStore.test.ts, src/storage/sets/flatbuffers/followStore.ts, src/storage/sets/flatbuffers/signerStore.test.ts, src/storage/sets/flatbuffers/signerStore.ts, src/storage/sets/flatbuffers/verificationStore.test.ts, src/storage/sets/flatbuffers/verificationStore.ts
See #199 
Renaming all other sets to stores
=> refactor(sets): rename flatbuffer sets to stores

src/hub.ts, src/network/sync/syncEngine.test.ts, src/network/sync/syncEngine.ts, src/storage/db/message.test.ts, src/storage/db/message.ts, src/storage/engine/index.ts, src/test/e2e/hub.test.ts
Ensure trie is in sync with the messages already present in the engine on hub boot. Otherwise, we'll perform redundant syncs just to populate the merkle trie. Note, this is slow. For better performance, we should optimize the trie and cache it on disk and use this codepath only to repair the trie. Will implement in a followup PR.
Iterate through all messages in the DB on boot and populate the merkle trie in the sync engine.
=> feat: initialize sync trie with existing messages on hub boot

codecov.yml
Patch failures cause a lot of false positives 
Decreasing coverage on a patch does not fail CI as long as overall test coverage is above the target
=> chore: do not fail coverage if patch is below target

.config/hub.config.ts, src/network/rpc/server.ts
AWS healthchecks fail on expoed ports if the application is not listening on IPv6.
=> fix(config): Default to IPv6 for Gossip and RPC 

src/hub.ts, src/network/p2p/node.ts
Hub's don't know their public addresses. Libp2p doesn't figure out the public IP correctly and so we need to have something to fall back on.
Since we bootstrap with a public multiaddr, libp2p should store that addr in the addressbook. 
This PR manually updates the addressbook to store the address of any open connections with a peer. 
=> fix(gossip): store addresses from existing connections into the address book

src/storage/flatbuffers/types.ts, src/storage/sets/flatbuffers/signerStore.ts, src/storage/sets/flatbuffers/verificationStore.test.ts, src/storage/sets/flatbuffers/verificationStore.ts
- fix: sorting of messages should be performed by timestamp, then type, then hash similar to other stores
- added documentation for classes and methods
- increase test coverage for branches in merge
=> fix(VerificationStore): increase test coverage, change conflict resolution, add docs

src/hub.ts, src/network/rpc/rpc.test.ts, src/network/sync/merkleTrie.test.ts, src/network/sync/merkleTrie.ts, src/network/sync/syncEngine.test.ts, src/network/sync/syncEngine.ts, src/network/sync/trieNode.ts, src/storage/db/message.test.ts, src/storage/db/message.ts, src/storage/engine/engine.cast.test.ts, src/storage/engine/engine.follow.test.ts, src/storage/engine/engine.reaction.test.ts, src/storage/engine/engine.revoke.test.ts, src/storage/engine/index.ts, src/storage/sets/castSet.ts, src/storage/sets/followSet.ts, src/storage/sets/reactionSet.ts, src/storage/sets/signerSet.ts, src/storage/sets/verificationSet.ts, src/test/e2e/differentialSync.test.ts, src/utils/errors.ts, src/utils/logger.ts
Diff sync must be able to handle deleted messages (e.g. from a signer remove) and converge to the same state. 
Sync engine listens for message deletions from the storage engine an deletes the item from the trie. Added tests to make sure hubs will converge to same state when they have deleted messages.
Also includes a other follow ups from review comments in https://github.com/farcasterxyz/hub/pull/179
=> feat: Handle message deletion in diff sync

package.json, src/hub.ts, src/network/p2p/connectionFilter.ts, src/network/p2p/node.ts, src/network/p2p/protocol.test.ts, src/network/p2p/protocol.ts, src/test/e2e/hub.test.ts, src/types/typeguards.ts, src/utils/p2p.test.ts, src/utils/p2p.ts
libp2p does not automatically resolve Peer's addresses. We needed a way to figure out how to reach peers discovered via Gossip. 
- Fetch public IP's using the [ipify.org](https://www.ipify.org/) API.
- Publish public IP's over gossip
=> feat(p2p): advertise public IP over gossip

src/network/p2p/node.test.ts, src/network/p2p/node.ts, src/utils/hubErrors.ts
See: https://github.com/farcasterxyz/hub/issues/213
Introduces a new error class (HubError), a new error cataloging system (HubErrorCodes) and a standard result type for error prone functions (HubResult) that is built on neverthrow's Result. Also refactors one arbitrary method to demonstrate the syntax of the method in the application and tests.
=> feat: prototype new error handling pattern and refactor one method to use it 

CONTRIBUTING.md, src/cli.ts, src/hub.ts, src/network/p2p/connectionFilter.ts, src/network/p2p/node.test.ts, src/network/p2p/node.ts, src/network/p2p/protocol.ts, src/network/rpc/client.ts, src/network/sync/syncEngine.ts, src/network/sync/syncId.ts, src/test/perf/bench.ts, src/utils/hubErrors.ts, src/utils/p2p.test.ts, src/utils/p2p.ts, src/utils/safe.ts
See: #213 
Refactors all files under network/p2p and utils/p2p to use HubResults and HubErrors for error handling
=> refactor(p2p): network/p2p uses HubResults and HubErrors

src/storage/sets/flatbuffers/followStore.test.ts, src/storage/sets/flatbuffers/followStore.ts, src/storage/sets/flatbuffers/reactionStore.ts, src/storage/sets/followSet.ts
Fixing an issue where follows set did not implement LWW-RW rules as intended, and refactoring the set to have more documentation and unit test coverage
See above
=> refactor(followStore): add unit test coverage, change conflict logic

src/storage/sets/flatbuffers/castStore.test.ts, src/storage/sets/flatbuffers/castStore.ts, src/storage/sets/flatbuffers/reactionStore.ts
Cast Store did not have full test coverage for all permutations of collisions
Added tests to coverage all edge cases and added documentation to explain the set behaviors.
=> test(CastStore): add coverage for edge cases

src/network/sync/merkleTrie.test.ts, src/network/sync/trieNode.test.ts, src/network/sync/trieNode.ts, src/test/factories.ts
Improves the trie memory efficiency by not creating nodes if there is only one value. Since our sync ids are long, and will very rarely collide, this should yeild substantial savings.
Previously, when inserting a key, the trie will create a node for each character in the key until the end of the string and then insert the value. Now, after the timestamp portion of the string, we'll immediately create a leaf node if it's the only value. Or split the node until they don't share a common prefix anymore and insert the value.
We're currently choosing not to copmact the timestamp portion of the trie, we could do it if we wanted to, but it breaks a lot of tests and the benefit in marginal.
=> perf: Improve trie memory efficiency

src/storage/flatbuffers/messageModel.ts, src/storage/sets/flatbuffers/castStore.test.ts, src/storage/sets/flatbuffers/castStore.ts
Pruned cast store implementation. See discussion of pruning here: https://hackmd.io/@farcasterxyz/BJj3zuVVj
* Add `pruneMessages` CastStore method that prunes messages by size and time
=> feat: prune messages in CastStore

src/network/rpc/flatbuffers/userDataService.test.ts, src/storage/engine/flatbuffers/index.ts, src/storage/sets/flatbuffers/userDataStore.test.ts, src/storage/sets/flatbuffers/userDataStore.ts
When processing `UserDataAdd` messages for `fname`, ensure that the fname is actually owned by the user.
- Ensure the custody address of the `fid` and the `fname` are the same, ensuring that the `fid` owns the `fname` at the time of processing
I've added the checks in the `UserDataStore` since it already throws HubError for validation, but I can also move it to the engine's `validateMessage`
=> fix:Ensure fname is owned when adding UserDataName

src/storage/flatbuffers/idRegistryEventModel.ts, src/storage/flatbuffers/nameRegistryEventModel.test.ts, src/storage/sets/flatbuffers/userDataStore.test.ts, src/storage/sets/flatbuffers/userDataStore.ts
When fname's are transfered, the corresponding `UserDataAdd` message from the previous owner needs to be revoked
- Use the new `IdRegistryEventModel.getByCustodyAddress` method to look up events by custody address to get the fid
- Remove the corresponding UserDataAdd message from the old user
=> fix: Delete UserDataAdd for fname when it is transfered

src/network/rpc/server.ts
The multiaddr was interpolating a Result object rather than the value inside the result, resulting in an incorrect mutliaddr string:
```
"[object Object]/tcp/50458"
```
Updated the multiaddr function to check the result of `ipMultiAddrStrFromAddressInfo` and if successful return a string with the result value interpolated in the multiaddr string, else return undefined.
=> fix(RPCServer): use result value instead of result in multiaddr str

src/hub.ts, src/network/p2p/node.test.ts, src/network/sync/syncEngine.test.ts, src/network/sync/trieNode.test.ts, src/network/sync/trieNode.ts, src/storage/flatbuffers/utils.ts, src/storage/provider/idRegistryProvider.ts, src/test/e2e/differentialSync.test.ts, src/test/e2e/hub.test.ts, src/test/perf/bench.ts, src/test/perf/setup.ts, src/test/perf/utils.ts, src/urls/castUrl.ts, src/urls/chainAccountUrl.ts, src/urls/chainUrl.ts, src/urls/userUrl.ts, src/urls/utils.ts, tsconfig.json
See #151 
Enables the `noUncheckedIndexedAccess` in `tsconfig.json`. Update usages of property accesses to comply, generally following the rule:
- in tests or util files, use `as`
- in application code, use runtime checks
=> chore: enable noUncheckedIndexedAccess

src/hub.ts, src/storage/engine/flatbuffers/providers/ethEventsProvider.test.ts, src/storage/engine/flatbuffers/providers/ethEventsProvider.ts
Fix a bug in the initial (historical) sync where a block might be missed
If a block is created just before we start historical sync, the earliest block might get missed. 
Follow up from #284
=> bugfix: Edge case where a block would not be synced

src/cli.ts, src/flatbuffers/hub.ts, src/storage/engine/flatbuffers/providers/ethEventsProvider.ts
Add the ETH network connection to the new Hub
Initialize and start the `ethEventsProvider` in the new hub.
Moving this over from the old hub to the new hub.
=> chore: Add Eth Network Provider to the new hub.

package.json, yarn.lock
Upgraded out of date packages to latest versions to keep ahead of latest changes.
All packages except libp2p were upgraded to latest successfully. libp2p was not attempted, and will be done in a separate pr.
=> chore: upgrade packages (dec 16, 2022)

src/network/rpc/flatbuffers/castService.test.ts, src/network/rpc/flatbuffers/eventService.test.ts, src/network/rpc/flatbuffers/followService.test.ts, src/network/rpc/flatbuffers/reactionService.test.ts, src/network/rpc/flatbuffers/signerService.test.ts, src/network/rpc/flatbuffers/submitService.test.ts, src/network/rpc/flatbuffers/syncService.test.ts, src/network/rpc/flatbuffers/userDataService.test.ts, src/network/rpc/flatbuffers/verificationService.test.ts, src/storage/engine/engine.verification.test.ts, src/storage/engine/flatbuffers/index.test.ts, src/storage/flatbuffers/validations.test.ts, src/storage/sets/flatbuffers/userDataStore.test.ts, src/test/factories/flatbuffer.ts, src/utils/eip712.test.ts
See https://github.com/farcasterxyz/hub/pull/295
Replaced all instances of `Wallet.createRandom()` with faster method to speed up tests
=> perf: replace all calls to Wallet.createRandom() to speed up tests

src/hub.ts, src/storage/engine/flatbuffers/providers/ethEventsProvider.ts, src/test/e2e/hub.test.ts
The original goal was to solve #297, but this change did not resolve the issue entirely. However, it is does clean up 9 event handlers that were not terminated, so it's worth merging anyway. 
EthEventListener implements a stop method which clears all listeners and the hub calls stop when it is stopped.
=> fix: clean up contract event handlers when stopping hub

src/network/p2p/node.test.ts
Speed up node tests locally from 22s -> 10s by eliminating unnecessary waits and re-initializations. 
- Two tests were combined to eliminate unnecessary double initialization
- Sleep times were reduced from 5s to2s since the network formed quickly
- `forEach` was replaced with `map` where iteration was not necessary
=> perf: speed up gossip node tests

.github/workflows/ci.yml, codecov.yml, src/network/p2p/node.test.ts
Tests are run in a GH Actions matrix using jest's default sharding behavior to speed up test runs. 
- CI runs are matrixed and sharded into two separate machines
- CI runs implement concurrency checks to prevent multiple test runs on the same branch.
=> perf: shard tests and run them as a matrix in CI

src/flatbuffers/hub.ts, src/storage/engine/flatbuffers/providers/ethEventsProvider.test.ts, src/storage/engine/flatbuffers/providers/ethEventsProvider.ts, src/test/e2e/hub.test.ts
Fixes #297
Properly teardown the `EthEventsProvider` when finishing the tests.
- Remove bootstrap poll and the regular poll in the JSONRpc Provider
=> Fix: Tests need to teardown properly.

README.md, src/cli.ts
The README for starting a Hub no longer works.
- Updated the README with instructions on getting and plugging in the Eth node url
- Updated the cli to throw an error if the node url is not provided
=> docs: README for starting the Hub correctly

.github/workflows/ci.yml
Resolves these warnings:
Upgrade all the GH actions to the latest versions
=> test: upgrade gh actions to resolve warnings

src/flatbuffers/hub.ts, src/network/rpc/flatbuffers/server.ts, src/network/rpc/flatbuffers/submitService.test.ts, src/storage/engine/flatbuffers/index.test.ts, src/storage/engine/flatbuffers/index.ts, src/storage/engine/flatbuffers/providers/ethEventsProvider.ts, src/storage/flatbuffers/idRegistryEventModel.test.ts, src/storage/flatbuffers/idRegistryEventModel.ts, src/storage/flatbuffers/messageModel.test.ts, src/storage/flatbuffers/messageModel.ts, src/storage/flatbuffers/nameRegistryEventModel.test.ts, src/storage/flatbuffers/nameRegistryEventModel.ts, src/storage/flatbuffers/types.ts, src/utils/logger.ts
We want to log both when messages/events are submitted to the hub (and by what source) as well as when messages/events are successfully merged
* Log events from StoreEventHandler as well as submitted messages and events in Hub
* Validate message and event types in constructor of MessageModel, IdRegistryEventModel, and NameRegistryEventModel
=> refactor: update logging for engine and hub

src/flatbuffers/utils/bytes.ts
Change the `toNumber` helper to use LE conversion instead of the previously incorrect BE conversion
=> fix: use little-endian conversion instead of big endian

src/flatbuffers/factories/flatbuffer.ts, src/flatbuffers/models/validations.test.ts, src/flatbuffers/models/validations.ts, src/flatbuffers/utils/bytes.test.ts, src/flatbuffers/utils/bytes.ts
We've encountered issues with padded vs unpadded fids. Fids should be unpadded little endian byte arrays.
* Add `numberToBytes` util method that converts a javascript number into an unpadded little endian byte array
* Expand `validateFid` method to return an error when the fid is padded
=> fix: numberToBytes method and validate fid is not padded

jest.config.ts, package.json, tsconfig.json, yarn.lock
Closes #314. Speed up `yarn test` by ~2x.
Replace `ts-jest` with `@swc/jest` to transform our TS files in Jest.
=> perf: use swc to transform TS in jest

.eslintrc.cjs, src/network/p2p/connectionFilter.test.ts
There were 10 lint warnings for unused variables. In all cases the variables were prefixed with _ indicating that they were unused. This configures the linting rule to respect the convention and flag violations as errors.
Configures the @typescript-eslint/no-unused-vars lint rule to ignore arguments that match `^_`. 
Removes unused variable declarations from `connectionFilter.test.ts`.
=> chore: configure no-unused-var to ignore '^_' args

src/flatbuffers/models/hubStateModel.ts, src/flatbuffers/models/idRegistryEventModel.ts, src/flatbuffers/models/messageModel.ts, src/flatbuffers/models/nameRegistryEventModel.ts
Build the byte representation of a flatbuffer from the `flatbuffers.Builder` instead of using the internal representation.
- This was causing a nasty bug which would sometimes when the byte representation was being sent over RPC. 
=> fix: Build flatbuffer byte representation from builder

src/flatbuffers/generated/rpc_generated.ts, src/flatbuffers/schemas/rpc.fbs, src/rpc/client/index.ts, src/rpc/server/serviceImplementations/eventImplementation.ts, src/rpc/test/ampService.test.ts, src/rpc/test/castService.test.ts, src/rpc/test/eventService.test.ts, src/rpc/test/reactionService.test.ts, src/rpc/test/signerService.test.ts, src/rpc/test/syncService.test.ts, src/rpc/test/userDataService.test.ts, src/rpc/test/verificationService.test.ts
We need to refactor EventResponse as well as MessagesResponse to nest the flatbuffer byte array directly rather than including the flatbuffer table.
* Update `EventResponse` flatbuffer to include `bytes: [ubyte]`
* Update gRPC events service to pack the message or event bytes
* Simplify gRPC tests now that MessagesResponse is fixed
=> refactor: update gRPC EventResponse to use bytes directly

src/flatbuffers/factories.ts, src/network/sync/merkleTrie.test.ts, src/network/sync/merkleTrie.ts, src/network/sync/syncEngine.test.ts, src/network/sync/trieNode.test.ts, src/network/sync/trieNode.ts
Remove the `value` field from the Merkle Trie used for sync, since it is the same as the `key`
- Remove the `value` field from the trie to save memory. 
=> chrore: Remove 'value' from merkleTrie

src/network/sync/syncEngine.test.ts, src/network/sync/syncEngine.ts, src/network/sync/syncId.ts, src/storage/stores/castStore.ts
Use `getFarcasterTime()` to get the current time instead of `Date.now()` when creating snapshots
We use farcaster time instead of wall time in message timestamps, so we should use the same to create the snapshots. 
=> chore: Use farcaster time when creating snapshots

src/flatbuffers/factories.ts, src/network/sync/multiPeerSyncEngine.test.ts, src/network/sync/syncEngine.test.ts, src/storage/stores/ampStore.ts, src/storage/stores/reactionStore.ts
Emit revoke messages from the engine when casts, amps and reactions are removed, so they can be updated in the sync Trie
- Emit 'revokeMessage' when casts, amps and reactions are removed
- Insert the revoked message into the trie and remove the corresponding add message from the trie.
- Add test for revoke
=> fix: Emit revoke messages when casts, reactions and amps are removed

app/src/hub.ts, app/src/hubRpcClient.ts, app/src/network/sync/multiPeerSyncEngine.test.ts, app/src/rpc/client/index.ts, app/src/rpc/client/serviceRequests/syncRequests.ts, app/src/rpc/server/index.ts, app/src/rpc/server/serviceImplementations/syncImplementation.ts, app/src/rpc/test/ampService.test.ts, app/src/rpc/test/castService.test.ts, app/src/rpc/test/eventService.test.ts, app/src/rpc/test/reactionService.test.ts, app/src/rpc/test/signerService.test.ts, app/src/rpc/test/submitService.test.ts, app/src/rpc/test/syncService.test.ts, app/src/rpc/test/userDataService.test.ts, app/src/rpc/test/verificationService.test.ts
Client is a folder that will be shared between consumers of the Hub and the Hub itself. It is important that this has as few external dependencies as possible so that it can be easily extracted into a package in the future. Closes #312 
The 'net', 'logger', 'utils/p2p' dependencies are removed from Client by refactoring hub specific logic into HubRPCClient and introducing ClientError.
=> refactor: minimize external dependencies in RPC client

app/src/hub.ts, app/src/storage/engine/index.ts, app/src/storage/jobs/pruneMessagesJob.test.ts, app/src/storage/jobs/pruneMessagesJob.ts, app/src/storage/jobs/revokeSignerJob.ts
We need to run pruneMessages task on a regular cadence.
* Add `PruneMessagesJobScheduler` class
* Instantiate `pruneMessagesJobScheduler` in hub and start/stop it accordingly
=> feat: add PruneMessagesJobScheduler

app/src/network/sync/multiPeerSyncEngine.test.ts, app/src/network/sync/syncEngine.ts, app/src/rpc/client/index.ts, app/src/rpc/server/index.ts, app/src/rpc/server/serviceImplementations/syncImplementation.ts, app/src/rpc/serviceDefinitions/syncDefinition.ts, package.json, packages/flatbuffers/src/generated/rpc_generated.ts, packages/flatbuffers/src/schemas/rpc.fbs
Fixes #363
A new RPC that allows clients to fetch a remote Hub's rootHash and the Trie snapshot at any prefix, so nodes can check if they need to sync in the first place. 
- New `getSyncTrieNodeSnapshotByPrefix` RPC
- Tests 
=> feat: RPC to get Trie snapshots/hashes

app/src/network/sync/merkleTrie.test.ts, app/src/network/sync/trieNode.test.ts, app/src/network/sync/trieNode.ts
Switch the Sync Trie hash to blake3 vs sha256
- Switch sha256 -> blake3
- 128-bit hash to compact trie
=> Blake3hash

app/src/utils/crypto.test.ts, app/src/utils/crypto.ts
Ethers.js `hexlify` uses big endian notation. Replace usage with bytes methods with explicit endianness.
=> refactor: purge hexlify usage

app/src/network/sync/syncEngine.ts, app/src/rpc/client/index.ts, app/src/rpc/server/index.ts, app/src/rpc/server/serviceImplementations/syncImplementation.ts
Encode everything as little endian for transport over flatbuffers
- Prefixes and hashes are encoded little endian over RPC in flatbuffers
- Update tests
=> chore: Encode prefixes and hashes as little endian

app/src/network/sync/merkleTrie.ts, app/src/network/sync/syncEngine.test.ts, app/src/network/sync/syncEngine.ts, app/src/network/sync/syncId.ts, app/src/network/sync/trieNode.test.ts
When fetching messages during syncing, sort them before merging. This causes the messages to be merged in 'correct' order - Like `SignerAdd` first, `Add*` before `Remove*` etc..., which reduces the need to refetch messages
- Sort messages by timestamp just before merging them sequentially. 
=> fix: Sort messages during sync to reduce refetching

app/src/cli.ts, app/src/hub.ts, app/src/network/sync/multiPeerSyncEngine.test.ts, app/src/network/sync/syncEngine.ts, app/src/rpc/client/index.ts, app/src/rpc/client/serviceRequests/syncRequests.ts, app/src/rpc/server/serviceImplementations/syncImplementation.ts, app/src/rpc/serviceDefinitions/syncDefinition.ts, packages/flatbuffers/src/generated/rpc_generated.ts, packages/flatbuffers/src/schemas/rpc.fbs
Add a new `getInfo` RPC to get information about Hub peers, including version and rootHash. 
- new `getInfo` RPC that returns Hub version, name, rootHash and other info
=> feat: Add getInfo RPC to get peer version and roothash

app/src/signers/eip712Signer.ts
`_unsafeWrap` should not be called outside of tests.
Remove `_unsafeWrap` usage from `Eip712Signer` constructor. Behavior stays the same.
Are there any thoughts by the core team on throwing in the constructor re #213?
=> refactor: remove _unsafeWrap usage from Eip712Signer constructor

app/src/flatbuffers/models/validations.test.ts, app/src/flatbuffers/models/validations.ts
`validateMessage` should validate all attributes of the message, not just the signatures and hashes.
* Call `validateFid` as part of `validateMessage` method
=> fix: validate fid as part of validateMessage

app/README.md
Fixing a markdown link I noticed that didn't work when trying out hubs.
Made the `setting up your environment` link point to the correct markdown document.
=> docs: fix contributing link in app/README.md

app/src/hub.ts, app/src/network/p2p/gossipNode.test.ts, app/src/network/p2p/gossipNode.ts, app/src/network/p2p/multiPeerGossip.test.ts, app/src/network/utils/factories.test.ts, app/src/network/utils/factories.ts, app/src/utils/logger.ts, packages/flatbuffers/src/generated/gossip_generated.ts, packages/flatbuffers/src/generated/message_generated.ts, packages/flatbuffers/src/generated/rpc_generated.ts, packages/flatbuffers/src/schemas/gossip.fbs, packages/flatbuffers/src/schemas/message.fbs, packages/flatbuffers/src/schemas/rpc.fbs
Add a multi-peer test that starts 2 full hubs and tests gossip over localhost tcp.
- New multi-peer test
- Switch to using `MessageBytes` instead of using a nested `Message` flatbufffer.
- rename 'Node' to `GossipNode`
=> test: Add multi-peer gossip test

apps/hub/.config/hub.config.ts, apps/hub/src/cli.ts, apps/hub/src/hub.ts, apps/hub/src/network/p2p/gossipNode.ts, apps/hub/src/network/p2p/multiPeerGossip.test.ts
When announcing out a node's address, we need to announce the node's public IP. We can either get this from an external service or have the user specify it
- `--announce-ip` config option to let the user tell us what the public IP is
- If not provided, fetch public IP from external service
- New `--no-fetch-ip` to prevent contacting external service.
=> feat: Fetch public IP to announce to peers

packages/utils/src/bytes.test.ts, packages/utils/src/bytes.ts
Makes byte utils non-mutating.
=> fix: make utils/bytes non-mutating

apps/hub/src/rpc/test/concurrency.test.ts, apps/hub/src/storage/engine/index.test.ts, apps/hub/src/storage/engine/index.ts, apps/hub/src/storage/stores/ampStore.ts, apps/hub/src/storage/stores/castStore.ts, apps/hub/src/storage/stores/reactionStore.ts, apps/hub/src/storage/stores/sequentialMergeStore.test.ts, apps/hub/src/storage/stores/sequentialMergeStore.ts, apps/hub/src/storage/stores/signerStore.ts, apps/hub/src/storage/stores/userDataStore.ts, apps/hub/src/storage/stores/verificationStore.ts
Closes https://github.com/farcasterxyz/hub/issues/178
* Add `SequentialMergeStore` class for stores to extend which forces messages to be merged sequentially
* Add test suite for concurrent merges via gRPC and to the engine directly
* Update `mergeMessages` engine method to run merges in parallel because the stores will handle the necessary sequencing
=> fix: force messages to be merged sequentially in stores

apps/hub/.config/hub.config.ts, apps/hub/src/cli.ts, apps/hub/src/eth/ethEventsProvider.test.ts, apps/hub/src/eth/ethEventsProvider.ts, apps/hub/src/hub.ts, apps/hub/src/network/p2p/multiPeerGossip.test.ts, apps/hub/src/network/sync/multiPeerSyncEngine.test.ts, apps/hub/src/network/sync/syncEngine.test.ts, apps/hub/src/rpc/test/ampService.test.ts, apps/hub/src/rpc/test/bulkService.test.ts, apps/hub/src/rpc/test/castService.test.ts, apps/hub/src/rpc/test/concurrency.test.ts, apps/hub/src/rpc/test/eventService.test.ts, apps/hub/src/rpc/test/reactionService.test.ts, apps/hub/src/rpc/test/signerService.test.ts, apps/hub/src/rpc/test/submitService.test.ts, apps/hub/src/rpc/test/userDataService.test.ts, apps/hub/src/rpc/test/verificationService.test.ts, apps/hub/src/storage/engine/index.test.ts, apps/hub/src/storage/engine/index.ts, apps/hub/src/storage/jobs/pruneMessagesJob.test.ts, apps/hub/src/storage/jobs/revokeSignerJob.test.ts, apps/hub/src/storage/stores/sequentialMergeStore.test.ts, apps/hub/src/storage/stores/userDataStore.test.ts, apps/hub/src/test/mocks.ts
Farcaster messages include a farcaster network (testnet, devnet, mainnet) in the message data. The engine should validate that messages being merged match their own network. Closes #321 
* Update cli to accept `--network` for farcaster network (mainnet = 1, testnet = 2, devnet = 3)
* Move cli eth RPC url argument from `--network-url` to `--eth-rpc-url` 
* Add check for network in engine's `validateMessage` method
=> feat: validate network in engine

apps/hub/src/network/sync/syncEngine.test.ts, apps/hub/src/storage/stores/ampStore.ts, apps/hub/src/storage/stores/castStore.ts, apps/hub/src/storage/stores/reactionStore.ts, apps/hub/src/storage/stores/userDataStore.ts, apps/hub/src/storage/stores/verificationStore.ts
Some messages that were removed (as a part of `resolveMergeConflicts` methods weren't getting removed from the SyncTrie
- Keep track of deleted messages and remove them from the Sync Trie.
=> fix: Some removed messages weren't getting removed in the Trie

apps/hub/src/rpc/test/userDataService.test.ts, apps/hub/src/storage/engine/index.ts, apps/hub/src/storage/stores/userDataStore.test.ts, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
Fix a bug where the the fname Uint8Array was not being interpreted as little endian.
Switch to using a plain Uint8Array.
- Uint8Array as little endian string.
- Show the actual fname in error messages that was failing validation
=> fix: Interpret fname Uint8Array as littleEndian

apps/hub/src/storage/stores/sequentialMergeStore.ts
The merge queue would sometimes get deadlocked when processing bad messages (i.e., Messages that would return errors when merged).
Two related issues: 
1. When a Message that returns an error when merged is submitted, it fails to merge as expected, but doesn't get removed from the merge queue, so all subsequent messages get stuck behind this failed message
2. If the `processNextMerge` fails, the `processMerges` returns but doesn't set the `mergeIsProcessing` to false, causing a deadlock which prevents any further messages from being merged. 
- Deque mergeIds from the merge queue before processing
- Set `mergeIsProcessing` to false when returning with error
=> fix: Merge queue would get deadlocked

.gitignore, Dockerfile
Fix #347 broken docker builds
- Update Dockerfile according to monorepo structure
- Use `turbo prune` to optimize docker build
Currently, the Docker build attempt to run `yarn build`, which compiles Typescript files into Javascript. But in the last stage of the Dockerfile, TS code of the hub is copied into the image and it is run with `tsx` instead of the JS compiled files.
I believed it is done in this way because the hub uses tsconfig's path aliases (i.e. `compilerOptions.paths`) to map `~` to the project root but this mapping isn't carried into the JS files generated by `tsc`. Therefore, the compiled JS files of hub can't be run directly with node because node can't resolve the imports. …
=> fix: docker builds are broken

packages/js/src/utils.test.ts, packages/js/src/utils.ts, packages/utils/src/factories.ts
Tests were missing for `deserializeIdRegistryEvent` and `deserializeNameRegistryEvent`.
- adds tests for `deserializeIdRegistryEvent` and `deserializeNameRegistryEvent`
- improve related factories
- organize functions in `utils.ts`
=> test: add tests for deserializeIdRegistryEvents and deserializeNameRegistryEvents

apps/hub/src/network/sync/merkleTrie.test.ts, apps/hub/src/network/sync/merkleTrie.ts, apps/hub/src/network/sync/multiPeerSyncEngine.test.ts, apps/hub/src/network/sync/syncEngine.test.ts, apps/hub/src/network/sync/syncEngine.ts, apps/hub/src/network/sync/trieNode.test.ts, apps/hub/src/network/sync/trieNode.ts, apps/hub/src/storage/db/rocksdb.ts
Fix #163 review and fix or suppress eslint-security warnings
Suppress all eslint warnings since they are false positives. Based on PR by @TimDaub. 
=> chore: fix and suppress eslint warnings

Dockerfile
For ease of getting started developing with zero configuration add a required flag.
Add the (now required) `--eth-rpc-url` flag to the default command.
=> fix: Add required `--eth-rpc-url` flag to Docker image default command

apps/hub/src/flatbuffers/models/types.ts, apps/hub/src/network/sync/syncEngine.ts, apps/hub/src/rpc/server/index.ts, apps/hub/src/rpc/test/concurrency.test.ts, apps/hub/src/rpc/test/submitService.test.ts, apps/hub/src/storage/db/rocksdb.ts, apps/hub/src/storage/engine/index.test.ts, apps/hub/src/storage/engine/index.ts, apps/hub/src/storage/jobs/revokeSignerJob.ts, apps/hub/src/storage/stores/ampStore.test.ts, apps/hub/src/storage/stores/ampStore.ts, apps/hub/src/storage/stores/castStore.test.ts, apps/hub/src/storage/stores/castStore.ts, apps/hub/src/storage/stores/reactionStore.test.ts, apps/hub/src/storage/stores/reactionStore.ts, apps/hub/src/storage/stores/sequentialMergeStore.test.ts, apps/hub/src/storage/stores/sequentialMergeStore.ts, apps/hub/src/storage/stores/signerStore.test.ts, apps/hub/src/storage/stores/signerStore.ts, apps/hub/src/storage/stores/storeEventHandler.ts, apps/hub/src/storage/stores/userDataStore.test.ts, apps/hub/src/storage/stores/userDataStore.ts, apps/hub/src/storage/stores/verificationStore.test.ts, apps/hub/src/storage/stores/verificationStore.ts, packages/utils/src/bytes.test.ts, packages/utils/src/bytes.ts, packages/utils/src/errors.ts, packages/utils/src/tsHash.test.ts, packages/utils/src/tsHash.ts
`mergeMessage` should only return ok if the message is successfully merged. If the message is a duplicate or conflicts with a later message, the store should return an error. Closes #423 
* Update all stores to throw hub error with error code `bad_request.duplicate` when duplicate message is submitted
* Update all stores to throw hub error with code `bad_request.conflict` when message is submitted that conflicts with a more recent existing message
* Update `mergeMessage` event to include array of deleted messages as well as the merged message and update the sync engine to remove messages when they are marked as deleted there
* Support passing `endianness` as option to `bytesIncrement` and `bytesDecrement`
_Choose all relevant options below by adding an `x` now or at any time before …
=> feat: update stores to return error statuses for duplicates and conflicts

apps/hub/package.json, apps/hub/src/cli.ts, apps/hub/src/console/castsCommand.ts, apps/hub/src/console/console.ts, apps/hub/src/console/infoCommand.ts, apps/hub/src/console/syncTrieCommand.ts, apps/hub/src/rpc/server/serviceImplementations/syncImplementation.ts
Add a debugging REPL to the hubs
- A new command `yarn console` will connect to the local Hub with the nodejs REPL.
- Several commands are available to inspect the Hub's internal state (".help" to see a list of commands)
eg: `hub> await syncTrie.rootHash()` will fetch the Hub's root hash. 
This connects to a running Hub over RPC, so you need to run it in a separate terminal window.
=> feat: Add debugging console REPL

apps/hub/src/storage/stores/signerStore.test.ts, packages/js/jest.config.ts, packages/js/src/builders.test.ts, packages/js/src/utils.test.ts, packages/js/src/utils.ts, packages/utils/src/crypto/eip712.test.ts, packages/utils/src/factories.ts, packages/utils/src/signers/eip712Signer.test.ts, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
closes #404 
- add validations on all serialization functions that take a hex value as input
=> fix: validate inputs before serialization in @farcaster/js

apps/hub/src/network/sync/syncEngine.test.ts
[see this convo](https://github.com/farcasterxyz/hub/pull/279#issuecomment-1385718251)
- removes unused test code
=> chore: clean up unused syncThreshold test in syncEngine

.changeset/tall-mirrors-smile.md, apps/hub/src/rpc/server/serviceImplementations/eventImplementation.ts, apps/hub/src/rpc/test/eventService.test.ts, packages/flatbuffers/src/generated/rpc_generated.ts, packages/flatbuffers/src/schemas/rpc.fbs, packages/grpc/src/client.ts, packages/grpc/src/requests/eventRequests.test.ts, packages/grpc/src/requests/eventRequests.ts, packages/grpc/src/requests/index.ts, packages/js/src/client.ts, packages/js/src/types.ts, packages/js/src/utils.test.ts, packages/js/src/utils.ts, packages/utils/src/factories.test.ts, packages/utils/src/factories.ts
Closes #402, adds event type filtering to complete part of #350
- exposes a `subscribe` method on `@farcaster/js` client
- add event filter to `subscribe`
- adds `deserializeEventResponse` to deserialize an EventResponse flatbuffer object into our JSON object types
Ideally the `subscribe` method in `@farcaster/js` would be wrapping the grpc call in some way and performing the deserialization. However, I was uncertain about the best way to do this without layering a potentially undesirable abstraction over the `ClientReadableStream` object being returned by the grpc client.
=> feat: add support for /subscribe gRPC method in @farcaster/js package

apps/hub/src/hub.ts
Initialize the sync engine at startup so the existing syncTrie loads correctly
- Call `syncEngine.initialize` on hub startup
=> fix: Init sync engine with hub start

apps/hub/src/network/sync/merkleTrie.test.ts, apps/hub/src/network/sync/syncId.ts, apps/hub/src/network/sync/trieNode.ts, packages/js/src/builders.ts, packages/js/src/utils.ts, packages/utils/src/crypto/ed25519.test.ts, packages/utils/src/crypto/eip712.test.ts, packages/utils/src/factories.test.ts, packages/utils/src/factories.ts, packages/utils/src/signers/ed25519Signer.test.ts, packages/utils/src/signers/eip712Signer.test.ts, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
Switch the Sync trie hash to be 20 bytes (160-bit)
- switch to blake3 160-bit hash for sync trie.
=> fix: Switch to 160-bit hash

packages/protobufs/package.json, packages/protobufs/src/generated/rpc.ts, packages/protobufs/tsup.config.ts, packages/protoutils/src/factories.test.ts
Fix an issue where esbuild would not work with the dynamic requires coming from grpc-js
- Add a tsup.config that injects the `require` shim needed 
More information about the problem here: https://github.com/sveltejs/kit/issues/2400
ES build PR that this is copied from: https://github.com/evanw/esbuild/pull/2067
Adding this as a separate PR so I can revert it easily later if needed.
=> fix: Add require shim to esbuild

apps/protohub/src/network/sync/trieNode.test.ts, apps/protohub/src/network/sync/trieNode.ts
Fix an issue where the Sync Trie was being incorrectly compacted
- Fix delete() to make sure the subtree can actually be compacted. 
=> fix: Fix bug where trie was being incorrectly compacted

apps/protohub/src/network/sync/syncEngine.ts, apps/protohub/src/network/sync/trieNode.test.ts, packages/protobufs/src/generated/message.ts, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/schemas/message.proto, packages/protobufs/src/schemas/rpc.proto
Swtich to returning unary `MessagesResponse` instead of `stream Message` from RPC methods
- Switch to unary `MessagesResponse` for RPC methods
- Fix some warnings
- SyncEngine changes to use the MessagesResponse
=> fix: Switch to Unary MessageResponse instead of streaming

apps/protohub/src/hub.ts, apps/protohub/src/network/sync/syncEngine.test.ts, apps/protohub/src/network/sync/syncEngine.ts, apps/protohub/src/rpc/client/index.ts, apps/protohub/src/rpc/server/index.ts, apps/protohub/src/storage/engine/index.test.ts, apps/protohub/src/storage/stores/ampStore.test.ts, apps/protohub/src/storage/stores/castStore.test.ts, apps/protohub/src/storage/stores/reactionStore.test.ts, apps/protohub/src/storage/stores/signerStore.test.ts, apps/protohub/src/storage/stores/userDataStore.test.ts, apps/protohub/src/storage/stores/verificationStore.test.ts, apps/protohub/src/test/mocks.ts, packages/protobufs/src/index.ts
Add the `HubRpcClient` class
- Add grpc Client
- Wrap it in a proxy that converts callbacks to async/await
- Prevent promise from throwing, use HubResult instead.
=> feat: Add protobufs client

apps/protohub/src/rpc/server/index.ts, apps/protohub/src/rpc/server/test/reactionService.test.ts, apps/protohub/src/storage/engine/index.ts
Move the reactions Service tests
- Add validations to the reactions store
- Move the reactions service test to protobufs
=> feat: Add the reactionService test

apps/hubble/src/console/syncTrieCommand.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/syncId.ts, apps/hubble/src/network/sync/trieNode.test.ts, apps/hubble/src/network/sync/trieNode.ts, apps/hubble/src/network/utils/factories.ts, apps/hubble/src/rpc/server/test/verificationService.test.ts, apps/hubble/src/storage/engine/index.ts, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/schemas/rpc.proto
Use `Uint8Array` of bytes instead of hex strings in Sync Tries
- Switch key to bytes instead of hex strings for memory efficiency
- Update tests and RPC protocol to use bytes for prefixes
=> feat: Use bytes instead of hex string for SyncIds

apps/hubble/src/rpc/server/test/concurrency.test.ts
Fixes #488
Fix the flaky concurrency test
- Fix signers for the cast messages
- Assert the actual messages returned.
=> fix: Fix flaky concurrency test

apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/trieNode.test.ts, apps/hubble/src/network/sync/trieNode.ts
Use hash bytes instead of hex strings to calculate a node's hash. 
- recalculateHash method to recalculate hashes if needed
- Use hash bytes instead of hex strings of child's hash
=> fix: Use hash bytes instead of hex string to calculate hashes

.gitignore, apps/hubble/src/eth/ethEventsProvider.ts
This PR resolves issue #317, related to injesting the event logs from smart contracts in batches, vs all at once.
tl;dr for #317 is that trying to injest hundreds of thousands of events in one go, can lead to timeout and associated bugs, but processing them in smaller batches will allow them to be processed easier
I updated the `syncHistoricalIdEvents` and `syncHistoricalNameEvents` functions to use a configurable batchSize parameter. This allows event logs to be injested in batches, vs all at once.
Along with that, although its outside of the scope of the issue, I added a section for Editor cache to the .gitignore, including .vscode, .idea, and .fleet, since I didn't want to accidentally commit my cache
_Choose all relevant options below by adding an `x` now or at any time before …
=> feat: injest ethEventsProvider event logs in batches

apps/hubble/src/network/sync/syncId.ts, apps/hubble/src/network/sync/trieNode.test.ts, apps/hubble/src/storage/db/idRegistryEvent.ts, apps/hubble/src/storage/db/message.ts, apps/hubble/src/storage/db/types.ts, apps/hubble/src/storage/stores/ampStore.ts, apps/hubble/src/storage/stores/castStore.ts, apps/hubble/src/storage/stores/reactionStore.ts, apps/hubble/src/storage/stores/signerStore.ts
To save 8 bytes in rocks DB keys, this PR:
1. Stores FID keys in messages as 32 bits
2. Don't use the "ts" part of the tshash in SyncID keys since the timestamp is also available.
- Change fid keys to 32 bits
- Use the hash instead of tsHash in the SyncID keys
- Reconstruct primary key from SyncIDs by inserting the timestamp again. 
=> feat: Use uint32 for fid keys + ts compression in SyncID keys

Dockerfile, package.json
Docker builds stopped working post repo rename from `hub` to `hubble`.
Fix the Docker image build.
N/A
=> fix: Docker image builds post Hub→Hubble rename

package.json, yarn.lock
We need this update to fix an issue with our builds that occurs on GitHub Actions only (cannot repro locally).
Based on [this issue](https://github.com/vercel/turbo/issues/3570#issuecomment-1413350084), this should be fixed in 1.7.3, but since that release is not available, we'll use the canary for now.
Updated Turbo to 1.7.3 canary build 1.
=> fix: Update Turbo 1.6.3 → 1.7.3.canary.1 to fix Docker builds

Dockerfile, package.json, yarn.lock
Our previous attempts to fix the build in 50cfacd5 and 1c932091 didn't work because we had a locally cached layer which lead to an older version of Turbo being used, which didn't suffer from this bug.
The workaround (for now) is to pin to 1.7.0 explicitly when installing `turbo` in the Docker build step (which previously wasn't using the version listed in `package.json`).
Pin Turbo to 1.7.0 and use that version when building the Docker file (specifically in stage 1 of the build).
=> fix: Pin Turbo to 1.7.0 to fix Docker builds

Dockerfile
Binding to the loopback interface doesn't work when running within a
container.
=> fix: Expose gossip protocol port outside of container by default

Dockerfile
A package removal in d21a8f2e caused the Docker build to start failing. Removing this line seems to fix it.
Removed a line referring to a directory that no longer existed during the build.
=> fix: Docker build failing after package removal

.github/workflows/ci.yml
To prevent accidental breakages, test our Docker builds on PRs.
This should be relatively fast thanks to GitHub Actions caching, and the fact that the NPM `rocksdb` package has a pre-built binary for x64, which is what `ubuntu-latest` runs.
Split out `analyze`, `build`, and `test` jobs from the `build_and_test` job.
=> chore: Test Docker builds in CI

.github/workflows/ci.yml
This doesn't appear to serve any purpose, since the second shard appears to run the same tests as the first shard. Either this is misconfigured or broken, but regardless it's confusing.
Remove the unnecessary flag.
=> chore: Remove shard flag from tests

apps/hubble/src/cli.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/trieNode.test.ts, apps/hubble/src/rpc/server/test/castService.test.ts, apps/hubble/src/rpc/server/test/eventService.test.ts, apps/hubble/src/storage/db/rocksdb.test.ts, apps/hubble/src/storage/db/rocksdb.ts
Suppress false positive security warning, documenting the reasons for each
See above
=> chore: suppress false positive security warnings

.gitignore, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/syncEnginePerf.test.ts, apps/hubble/src/network/sync/trieNode.ts
Addresses some of the issues in #536. Cherry-picked test from @kcchu 
When syncing, use the same prefix as the remote snapshot to make sure we don't have any time differences.
- `performSync` and `shouldSync` now use the same prefix as the remote snapshot's to make sure there are no time discrepencies
- Cherry pick tests from @kcchu to check num of calls to fetch messages.
=> fix: Use other snapshot prefix when syncing

apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts
Parallelize and batch fetching missing SyncIDs so we don't take up too much memory
- Fetch missing messages as we discover them
- Fetch missing nods in parallel batches
- Fix some warnings in tests.
=> fix: Fetch missing SyncIDs in parallel batches

apps/hubble/src/hubble.ts, apps/hubble/src/rpc/server/index.ts
Gossip messages out only if we get them via RPC. Messages received via other nodes or during sync should not be gossiped out. 
- Move `gossipMessage` to server/index.ts
=> feat: Gossip only messages submitted via RPC

apps/hubble/src/test/e2e/gossipNetwork.test.ts
The [inbound connection limit change](https://discuss.libp2p.io/t/dialing-a-node-from-5-nodes-stopped-working-between-0-39-5-and-0-42-2/1811/3) was preventing the e2e test with 10 nodes from running successfully 
See above
=> fix: e2e tests should validate a network of 10 nodes

apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEnginePerf.test.ts, apps/hubble/src/network/sync/trieNode.ts
Fix 2 additional bugs discovered during SyncEngine benchmarking and discussed in #536
* Fix `getSnapshot` returning non-existent prefix in some cases (#536)
* Refactor `getSnapshot` to make it more readable
* Fix `getAllValues` not working if child nodes are not loaded
* Add test cases for `getAllValues` case
=> fix: 2 bugs that cause sync to run incorrectly

apps/hubble/src/network/sync/mock.ts, apps/hubble/src/network/sync/syncEnginePerf.test.ts, apps/hubble/src/test/bench/helpers.ts, apps/hubble/src/test/bench/index.ts, apps/hubble/src/test/bench/syncEngine.ts
Add Sync Engine benchmark script (#445)
Add SyncEngine simulation. It is a round-based test (not CPU bound). This test aims at measuring the performance of the sync algorithm. Number of RPC are measured, which can be used to estimate the performance in a network-bounded situation.
1. Pre-generate 10,000 messages and populate `peersCount` SyncEngine instances.
2. For each round `1..count`:
1. Generate `round * cycle` new messages
2. Add messages to each peers with `dropRate` chance of dropping that message
3. For each SyncEngine, randomly pick another SyncEngine and perform sync.
4. Measure number of RPC requests and estimate binary entropy of the network after each
round.
5. Repeat each …
=> Add Sync Engine benchmark script

.github/workflows/ci.yml
Temporarily disable the "audit"  part of the github action to disable a spurious `yarn audit` failures
- Disable audit in the analyze github action
=> fix: Disable audit in github actions

apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts
Remove the `--no-fetch-ip` arg, and infer it if no `--announce-ip` is provided
- Remove `--no-fetch-ip`, it will be implied based on `--announce-ip`
=> fix: Remove --no-fetch-ip arg

apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/trieNode.test.ts, apps/hubble/src/network/sync/trieNode.ts
Unload the trie from memory and into DB
- Occasionally unload the Trie into DB, to clean up memory. 
=> feat: Unload Trie from memory

apps/hubble/src/storage/jobs/updateNameRegistryEventExpiryJob.ts
There's an occasional crash in `UpdateNameRegistryEventExpiryJob`. I'm not 100% sure what's casusing it, but I decided to wrap it in a HubError and log it so we can debug more. 
```
[08:23:56.713] FATAL (5032): index out of range: 4 + 52941 > 26
err: {
"type": "RangeError",
"message": "index out of range: 4 + 52941 > 26",
"stack":
RangeError: index out of range: 4 + 52941 > 26
at indexOutOfRange (file:///home/adityapk/github/farcaster/hub/packages/protobufs/dist/index.mjs:1847:14)
at Reader.read_bytes [as bytes] (file:///home/adityapk/github/farcaster/hub/packages/protobufs/dist/index.mjs:1984:15)
at Object.decode (file:///home/adityapk/github/farcaster/hub/packages/protobufs/dist/index.mjs:5686:34)
at <anonymous> (/home/adityapk/github/farcaster/hub/apps/hubble/src/storage/jobs/updateName …
```
=> fix: Occasional crash in UpdateNameRegistryEventExpiryJob

apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.test.ts, apps/hubble/src/network/p2p/gossipNode.ts, apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/periodSyncJob.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/syncEnginePerf.test.ts, apps/hubble/src/network/sync/trieNode.ts
Use a node-cron job to schedule periodic syncs with peers
- Use node-cron to schedule jobs for sync
- Make sure to use the leaf node's excludedHash as well
- Minor test fixes
=> feat: Use cron jobs to schedule peer syncs

.changeset/eight-bats-leave.md, packages/js/src/builders.test.ts, packages/js/src/types.ts, packages/js/src/utils.ts, packages/protobufs/src/generated/message.ts, packages/protobufs/src/schemas/message.proto, packages/utils/src/factories.ts, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
We can avoid including tokens (like `%0%`) in cast text by storing the positions of mentions in a separate list.
* Add `mentions_positions` list to CastAddBody schema
* Validate that positions are integers, in-range of text, and the same number as mentions
=> feat: add mentionsPositions to CastAddBody

apps/hubble/src/network/sync/periodSyncJob.ts, apps/hubble/src/storage/jobs/revokeSignerJob.ts, apps/hubble/src/storage/jobs/updateNameRegistryEventExpiryJob.ts
Recently, we've had a handful of fatal errors show up. After further investigation, these seem to be caused by sloppiness on my part because both RevokeSigner jobs and UpdateNameRegistryEventExpiry jobs were using the same job key prefix. So we'd get out of range errors when a RevokeSigner worker tried to decode what was actually an UpdateNameRegistryEventExpiry payload. 
* Change UpdateNameRegistryEventExpiry job prefix to unique key
=> fix: resolve out of range errors

apps/hubble/src/eth/ethEventsProvider.test.ts, apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/hubble.ts, apps/hubble/src/storage/stores/userDataStore.ts
We should ingest Renew events coming from the NameRegistry contract as well as Transfer events.
* Cache renew events from the contract
* When a new renew event is ready to merge, update the relevant NameRegistryEvent with the new expiry and block info
=> feat: support Renew events from the name registry contract

apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/syncId.ts, apps/hubble/src/storage/db/types.ts, apps/hubble/src/storage/engine/index.ts
Detect unclean shutdown and rebuild Trie if needed
- `--rebuild-sync-trie` CLI option
- Detect unclean shutdown via new RootPrefix
=> feat: Detect unclean shutdown and rebuild trie CLI option

apps/hubble/src/network/sync/syncEngine.ts
Write a log warn message if a sync'd message fails to merge. 
- `log.warn` if a sync message fails to merge
=> fix: Log failed sync message that didn't merge

apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/periodicSyncJob.ts, apps/hubble/src/network/sync/syncEngine.ts
Store peer contact info and get RPC clients on demand instead of storing the RPC clients themselves, since the RPC proxy client keeps an open connection and can timeout. 
- Store peer contacts instead of stateful RPC clients
- Create RPC clients on demand
=> fix: Store peer contacts instead of RPC proxy objects

.changeset/silly-trees-tickle.md, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
Since a cast could consist of just a mention, a valid cast can have no actual text (i.e. is the empty string), only a mention.
Don't fail validation if an empty text string is provided for the cast.
=> fix: Allow empty cast text

.changeset/slimy-jobs-do.md, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
It is possible for a cast to have multiple mentions with the same position. Consider the following cast:
@a@b@c
In this case, we are mentioning the users `a`, `b`, and `c`, without separating their names with any other text. The resulting `mentionsPositions` will be `[0, 0, 0]`, since there is no change in position.
Relax our validations to allow this case.
=> fix: Allow duplicate `mentionsPositions`

apps/hubble/src/console/adminCommand.ts, apps/hubble/src/console/console.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/rpc/server/adminServer.ts, apps/hubble/src/storage/engine/index.ts, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/index.ts, packages/protobufs/src/schemas/rpc.proto
Add a new 'admin' command for `yarn console` that lets you do delete messages and rebuild sync trie. Available only if you run it on the same machine as the server (no remote access)
- Add Admin service, bind it to unix file system socket
- rebuild command and delete all messages command. 
=> feat: Add admin debug commands

apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/test/bench/syncEngine.ts
If the merge stores are backed up and new messages are about to be timedout, we drop gossiped messages. They will be fetched with the next sync 
- Drop gossip messages if merge Q is full. 
=> feat: Implement rate limits for gossip/sync

packages/js/docs/modules.md, packages/js/src/builders.ts
Continue documenting the JS package. See: https://github.com/vinliao/hubble/blob/md-docs-2/packages/js/docs/modules.md#functions
Added a bunch of TSDoc comments on `builders.ts` and generated docs with `yarn docs`. Removed all "Data" functions (stuffs that end with "data").
Wondering if `makeMessageHash` and `makeMessageHashWithSignature` should be ignored in the docs because it seems to be a low-level utility function that JS devs won't touch.
=> docs: add JS docs to message builders

.changeset/great-eagles-explain.md, .changeset/hot-pigs-wave.md, .changeset/poor-bears-thank.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json, packages/js/CHANGELOG.md, packages/js/package.json, packages/protobufs/CHANGELOG.md, packages/protobufs/package.json, packages/utils/CHANGELOG.md, packages/utils/package.json
Since we have removed amps and location for UserData, we want to ensure our types on the backend are up to date.
Ran `yarn changeset version`
=> chore: bump changeset versions

apps/hubble/src/cli.ts, apps/hubble/src/eth/ethEventsProvider.test.ts, apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/hubble.ts
Exposing this will allow developers to create fully isolated testing environments if they wish to run a hub against a local/private Ethereum node (resolves #622). 
Expose all of `GoerliEthConstants` as CLI options.
https://github.com/farcasterxyz/hubble/blob/a237a6554a12d8822e74271d943169a355efdb8f/apps/hubble/src/eth/ethEventsProvider.ts#L14-L19
In the future, I think it will be worth adding an abi override option for testing changes to `farcasterxyz/contracts`. This feels less important in the current state as I imagine the vast majority of cases using this feature will be to reproduce production.
=> feat: add ability to change contract configuration via cli

apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/console/console.ts, apps/hubble/src/console/genCommand.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.test.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/rpc/server/index.ts, apps/hubble/src/rpc/server/test/bulkService.test.ts, apps/hubble/src/rpc/server/test/castService.test.ts, apps/hubble/src/rpc/server/test/concurrency.test.ts, apps/hubble/src/rpc/server/test/eventService.test.ts, apps/hubble/src/rpc/server/test/reactionService.test.ts, apps/hubble/src/rpc/server/test/rpcAuth.test.ts, apps/hubble/src/rpc/server/test/signerService.test.ts, apps/hubble/src/rpc/server/test/submitService.test.ts, apps/hubble/src/rpc/server/test/userDataService.test.ts, apps/hubble/src/rpc/server/test/verificationService.test.ts, packages/js/src/client.ts, packages/protobufs/src/index.ts, packages/utils/src/client.ts
Add SSL and basic auth to submit methods so only authorized users can submit to the Hub
-Add SSL support for clients
- Add optional basic auth for submit methods
=> feat: Add RPC Auth and SSL support

hideSig.js, packages/js/README.md, packages/js/docs/README.md, packages/js/docs/classes/Client.md, packages/js/docs/classes/Ed25519Signer.md, packages/js/docs/classes/Eip712Signer.md, packages/js/docs/interfaces/protobufs.AdminServiceClient.md, packages/js/docs/interfaces/protobufs.HubServiceClient.md, packages/js/docs/modules.md, packages/js/docs/modules/protobufs.md, packages/js/docs/modules/utils.md, packages/js/src/builders.ts, packages/js/src/client.ts, packages/js/src/signers.ts, packages/utils/src/signers/ed25519Signer.ts, packages/utils/src/signers/eip712Signer.ts, typedoc.json
#614. Current iteration: https://github.com/vinliao/hubble/blob/md-docs-hide-sig-2/packages/js/docs/modules.md#functions.
Remove the types in docs by adding a `hideSig.js` TypeDoc plugin and using it.
=> docs: remove verbose types

.changeset/ten-shrimps-know.md, packages/utils/src/bytes.ts, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
We want to know exactly how many bytes we're storing.
Furthermore, we want to guarantee that regardless of future iterations to the Unicode specification that we have an unambiguous way to take text and mention positions and reconstruct cast text from that by inserting dynamic content at those positions (e.g. username, which can change).
Check using utf8 byte length instead of character length.
While here, based on a team discussion and existing cast data we also increased the maximum number of mentions from 5 to 10.
=> fix: validate length limits in terms of utf8 bytes and allow up to 10 mentions

.changeset/old-dancers-promise.md, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
We want to ensure these URLs remain under 256 bytes when encoded as utf8.
Check that each embed URL has at least one byte and at most 256 bytes when encoded as utf8.
=> fix: Validate embed URLs using utf8 byte length

apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/utils/crypto.ts
Handle a rare case of timeout while quitting the hub. 
- catch timeouts while shutting down
=> fix: Catch timeouts during shutdown

.changeset/long-moles-buy.md, packages/protobufs/src/generated/message.ts, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/schemas/message.proto, packages/protobufs/src/schemas/rpc.proto, packages/utils/src/builders.test.ts, packages/utils/src/validations.test.ts, packages/utils/src/validations.ts
Closes https://github.com/farcasterxyz/hubble/issues/644
* Make `name` optional to avoid writing empty strings to protobufs
* Validate SignerAddBody `name` is either undefined or a string (1-32 bytes)
* Make `fromId` optional in SubscribeRequest
=> feat: make name and fromId optional

package.json, yarn.lock
Upgrade typescript to the final stable release before hub launch.
- Upgrade TS to v5.0.2
=> chore: upgrade typescript to v5 from v5beta

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
See title
- Added instructions on how to make and release changesets
- Addes checklist for requiring changeset in PR template
=> chore: add instructions and nudges to add changesets

apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/console/console.ts, apps/hubble/src/hubble.ts, apps/hubble/src/rpc/adminServer.ts
Run the Admin server on localhost only, gated by flag. 
- Move admin server to localhost port
- --admin-server-enabled flag has to be passed in to turn it on (off by default)
=> feat: Admin server on localhost only

.changeset/breezy-glasses-search.md, apps/hubble/src/network/p2p/gossipNode.ts, apps/hubble/src/network/sync/merkleTrie.ts
Increase sync trie Q size
- Sync Q size 1000 -> 10_000
- Trie node cache 10_000 -> 25_000 
=> fix: Increase Q limits now that we have more memory.

.changeset/weak-cameras-press.md, apps/hubble/src/hubble.ts
Attempt to retry rocksDB opening. Useful if the underlying filesystem is EFS
- Retry upto 5 times the DB.open()
=> feat: Retry rocksDB lock during open

.changeset/forty-zoos-tan.md, apps/hubble/package.json, apps/hubble/src/eth/ethEventsProvider.test.ts, apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/eth/utils.test.ts, apps/hubble/src/eth/utils.ts, packages/hub-nodejs/docs/Builders.md, packages/hub-nodejs/docs/Messages.md, packages/hub-nodejs/docs/Utils.md, packages/hub-nodejs/docs/signers/Eip712Signer.md, packages/hub-nodejs/examples/write-signer.md, packages/hub-nodejs/package.json, packages/utils/package.json, packages/utils/src/builders.test.ts, packages/utils/src/bytes.test.ts, packages/utils/src/bytes.ts, packages/utils/src/crypto/ed25519.test.ts, packages/utils/src/crypto/eip712.test.ts, packages/utils/src/crypto/eip712.ts, packages/utils/src/factories.ts, packages/utils/src/signers/ed25519Signer.test.ts, packages/utils/src/signers/eip712Signer.test.ts, packages/utils/src/signers/eip712Signer.ts, packages/utils/src/verifications.ts, yarn.lock
- Ethers v6 uses noble crypto instead of elliptic, which avoids issues [like this one](https://github.com/indutny/elliptic/issues/301) (cc @CassOnMars) 
- Ethers v6 will introduce breaking changes to our library so best to get it out before launch vs after. 
The downside is that we may be introducing some last minute bugs here which can go undetected, so I'd like to get some second opinions from folks working in the codebase. 
The most significant changes being made are: 
**JS BigInt instead of Ethers.BigNum**
BigInt seems like a drop in replacement except for the fact that serialization returns odd-length hex values like 0x3e8 instead of 0x03e8. In some cases this needs to be sanitized because parts of our codebase expect even length values. 
**Providers are very different under the …
=> refactor: update ethers to v6.1 from v5.7

apps/hubble/src/cli.ts
Add a 30s grace period after receiving a shutdown signal before forcing exit
- Add 30s timeout for SIGINT, SIGTERM and SIGQUIT
- Force exit at end of 30s
=> fix: Add a grace period before forcing exit after signals

apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/storage/db/message.ts, apps/hubble/src/storage/db/nameRegistryEvent.test.ts, apps/hubble/src/storage/db/nameRegistryEvent.ts, apps/hubble/src/storage/db/rocksdb.test.ts, apps/hubble/src/storage/db/rocksdb.ts, apps/hubble/src/storage/engine/index.ts, apps/hubble/src/storage/jobs/pruneMessagesJob.ts, apps/hubble/src/storage/jobs/revokeSignerJob.ts, apps/hubble/src/storage/jobs/updateNameRegistryEventExpiryJob.ts, apps/hubble/src/storage/stores/castStore.ts, apps/hubble/src/storage/stores/reactionStore.ts, apps/hubble/src/storage/stores/signerStore.ts, apps/hubble/src/storage/stores/storeEventHandler.ts, apps/hubble/src/storage/stores/userDataStore.ts, apps/hubble/src/storage/stores/verificationStore.ts
The RocksDB iterator doesn't seem to be release the natively-allocated memory unless end() is called explicitly. 
- Call iterator.end() explicitly 
=> fix: Fix memory leak in prune messages job

.changeset/funny-ears-compare.md, apps/hubble/src/cli.ts
Using `fs.watch` uses `inotify`, which doesn't work with network file systems like EFS where other kernels could be responsible for changes to the file system.
Instead, check every 10 seconds to see if there is a change.
=> fix: Switch to time-based check for process shutdown file

packages/protobufs/src/index.ts
Correctly fallback if SSL client fails
- Try to get SSL client
- Timeout after 2 seconds
- Fall back to Insecure client.
=> fix: Correctly get SSL / Insecure client

.changeset/clever-seals-greet.md, apps/hubble/src/hubble.ts
This makes it easier to set the name when deploying multiple hubs.
Add support for reading name from the `HUBBLE_NAME` environment variable.
=> chore: Allow specifying hub name via environment variable

apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts, apps/hubble/src/rpc/adminServer.ts, apps/hubble/src/storage/engine/index.ts
Fix an issue where the hub wouldn't start without a ethRPC URL. During tests, we don't connect to a ethRPC URL, so the hub should be able to start without one. 
- Allow hubs to startup without a ethRPC URL. 
- Show warning when starting without a ethRPC url
=> fix: Fix issue with ethers v6

apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.ts, apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/syncEnginePerf.test.ts, apps/hubble/src/network/sync/trieNode.test.ts, apps/hubble/src/network/sync/trieNode.ts, apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
Add a simple cache to the sync trie to prevent writing to RockDB every time. 
- Add write cache
- Commit to DB when unloading trie. 
=> fix: Add a simple cache to the sync trie

.changeset/famous-chefs-nail.md, apps/hubble/src/cli.ts, apps/hubble/src/console/console.ts, apps/hubble/src/console/genCommand.ts, apps/hubble/src/hubble.ts, apps/hubble/src/rpc/adminServer.ts, apps/hubble/src/rpc/server.ts, packages/utils/src/client.ts
Allow rpcAuth to be set via 'RPC_AUTH' env variable
- Accept RPC_AUTH via env variable
=> feat: Allow setting rpcAuth via env variables

apps/hubble/src/storage/stores/castStore.test.ts, apps/hubble/src/storage/stores/castStore.ts, apps/hubble/src/storage/stores/reactionStore.test.ts, apps/hubble/src/storage/stores/reactionStore.ts
We want all list methods to return messages sorted by timestamp. The cast and reaction indices thus far have returned messages grouped by fid and/or reaction type and then ordered by timestamp.
* Refactor cast indices to put tsHash before fid
* Refactor reaction indices to put tsHash before fid and put type in the value and filter on it
=> feat: sort casts and reactions indices by timestamp

packages/hub-nodejs/docs/Builders.md, packages/hub-nodejs/docs/signers/EthersEip712Signer.md, packages/hub-nodejs/docs/signers/NobleEd25519Signer.md
- updates `makeSignerAdd` and `makeSignerRemove` examples to make it clear an Ed25519 public key hex string is the input to the `signer` property of `SignerAddBody` and `SignerRemoveBody`
- consistent handling of `HubAsyncResult` in signer examples
=> docs: minor adjustments to signer related docs

.changeset/wise-sloths-tan.md, apps/hubble/src/eth/ethEventsProvider.test.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.test.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEnginePerf.test.ts, apps/hubble/src/rpc/test/bulkService.test.ts, apps/hubble/src/rpc/test/castService.test.ts, apps/hubble/src/rpc/test/concurrency.test.ts, apps/hubble/src/rpc/test/eventService.test.ts, apps/hubble/src/rpc/test/reactionService.test.ts, apps/hubble/src/rpc/test/rpcAuth.test.ts, apps/hubble/src/rpc/test/signerService.test.ts, apps/hubble/src/rpc/test/submitService.test.ts, apps/hubble/src/rpc/test/userDataService.test.ts, apps/hubble/src/rpc/test/verificationService.test.ts, apps/hubble/src/storage/engine/index.test.ts, apps/hubble/src/storage/engine/index.ts, apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts, apps/hubble/src/storage/jobs/revokeSignerJob.test.ts, apps/hubble/src/test/mocks.ts
Terminate web worker at end of tests and when hubble is shutting down
- Add webworker.terminate() in stop()
=> fix: Terminate webworker at end of tests

packages/hub-nodejs/docs/README.md, packages/hub-nodejs/docs/signers/EthersEip712Signer.md
Help users on Ethers v5 start using hub-nodejs without having to upgrade.
Added documentation to explain how to write a new class to use Ethers v5.
No changeset since this is a docs PR.
=> docs(hub-nodejs): configuration for use with ethersv5

packages/hub-nodejs/docs/Client.md, packages/hub-nodejs/examples/chron-feed/index.ts
Documents reverse sorting introduced in #695 
- Added documentation to Client for methods that support reverse 
- Fixed chron-feed example to return a reverse chron feed
No changeset for doc PRs
=> docs(hub-nodejs): add docs for reverse param

.changeset/wise-peaches-remain.md, apps/hubble/src/cli.ts
Reset DB if DB_RESET_TOKEN is set
- If DB_RESET_TOKEN is set and its value is different from what it was the last time the DB started, reset the DB. 
- Write value of DB_RESET_TOKEN to disk to remember for next restarts
=> feat: Reset DB if DB_RESET_TOKEN is set

.changeset/hungry-nails-collect.md, packages/utils/src/crypto/eip712.ts, packages/utils/src/signers/ethersEip712Signer.ts
Use type-only import (e.g. `import type`) to import `Signer` from ethers. This will avoid pulling in the entire `Signer` class and its dependencies at compile time.
Add `MinimalEthersSigner` that only contains the class we care about.
=> chore: use subset of ethers Signer class

apps/hubble/src/hubble.ts, apps/hubble/src/storage/engine/index.test.ts, apps/hubble/src/storage/engine/index.ts, apps/hubble/src/storage/engine/storageCache.test.ts, apps/hubble/src/storage/engine/storageCache.ts, apps/hubble/src/storage/jobs/pruneMessagesJob.ts, apps/hubble/src/storage/stores/castStore.ts, apps/hubble/src/storage/stores/reactionStore.ts, apps/hubble/src/storage/stores/signerStore.ts, apps/hubble/src/storage/stores/storeEventHandler.ts, apps/hubble/src/storage/stores/userDataStore.ts, apps/hubble/src/storage/stores/verificationStore.ts, packages/utils/src/factories.ts
Keep track of message counts per fid and store to speed up pruning.
* Add `StorageCache` class that when started keeps track of the number of messages for each fid/store in memory
* Use values from storage cache when pruning to avoid having to count messages live
* Make storage engine startable and stoppable, and start validation worker and add listeners on start
=> feat: add storage cache to speed up pruning

.changeset/healthy-poems-compare.md, apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts, apps/hubble/src/utils/periodicTestDataJob.ts, packages/hub-nodejs/examples/write-data/index.ts
Setting the "TEST_USERS" environment variables in a hub running in testnet will add some casts/reactions to those users every 30 minutes
- Set TEST_USERS to `{fid: number, mnemonic: string}[]`
- Every 30 minutes, add some casts and reactions to the users
=> feat: Add test data into test hubs

.changeset/spicy-ants-sin.md, apps/hubble/package.json, apps/hubble/src/rpc/server.ts, apps/hubble/src/rpc/test/rpcAuth.test.ts, yarn.lock
Add ip based rate limits for submitMessage. Currently 20k messages/min
- Add IP based rate limiting
=> feat: IP based rate limiting for submitMessage RPC

packages/hub-nodejs/README.md, packages/hub-nodejs/docs/Client.md
Update docs to reflect recent changes.
- Update the RPC ports to the new value
- Explain that hubs have rate limits for `submitMessage`
- Explain why Clients return generic Message objects and how to convert them to specific Message types
No changesets for docs PRs
=> docs(hub-nodejs): small cleanups and improvements 

.changeset/ten-ducks-roll.md, apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/utils/p2p.ts, packages/protobufs/src/generated/gossip.ts, packages/protobufs/src/schemas/gossip.proto
When SSL/TLS is enabled, we also need the server name to be gossiped, so clients can actually check the SSL cert.
- add `dnsName` to contact info gossip
- Allow setting `--announce-server-name` to set DNS name of server
=> fix: Share dns name when gossiping contactinfo

.changeset/witty-trainers-bake.md, packages/hub-nodejs/README.md, packages/hub-nodejs/docs/Client.md, packages/hub-nodejs/examples/README.md, packages/hub-nodejs/examples/chron-feed/README.md
Fixing issues discovered from having users play around with the docs.
- `submitMessage` signature was documented incorrectly
-  links to feed example and stackblitz were broken
- relative links were not working on the lib's npm page
=> docs(hub-nodejs): more cleanup based on user testing

packages/hub-nodejs/docs/Builders.md, packages/hub-nodejs/docs/Client.md, packages/hub-nodejs/docs/Utils.md, packages/hub-nodejs/docs/signers/EthersEip712Signer.md, packages/hub-nodejs/docs/signers/EthersV5Eip712Signer.md
More cleanups for documentation. 
- document unsafeUnwrap usage consistently
- replace all instances of `Buffer.from` with `hexStringToBytes`
No changeset for docs only PRs
=> docs(hub-nodejs): more cleanups and fixes

.changeset/tame-avocados-develop.md, apps/hubble/package.json, packages/hub-nodejs/package.json, packages/utils/package.json, yarn.lock
Ethers 6.x threw an unhandled exception if the RPC connection was open due to a listener and the server errored out. See: https://github.com/ethers-io/ethers.js/issues/3924 
Upgrade ethers to 6.2.1
=> fix(hubble): crash by bumping ethers to 6.2.1

packages/hub-nodejs/docs/Messages.md
`parentCastId` of CastAdd was incorrectly labelled as `parent`
See title
No changeset for docs prs
=> docs(hub-nodejs): fix parentCastId of CastAdd incorrectly labelled

apps/hubble/src/storage/db/message.ts, apps/hubble/src/storage/engine/index.test.ts, apps/hubble/src/storage/engine/index.ts, apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts, apps/hubble/src/storage/stores/castStore.test.ts, apps/hubble/src/storage/stores/castStore.ts, apps/hubble/src/storage/stores/reactionStore.test.ts, apps/hubble/src/storage/stores/reactionStore.ts, apps/hubble/src/storage/stores/signerStore.test.ts, apps/hubble/src/storage/stores/signerStore.ts, apps/hubble/src/storage/stores/storeEventHandler.test.ts, apps/hubble/src/storage/stores/storeEventHandler.ts, apps/hubble/src/storage/stores/types.ts, apps/hubble/src/storage/stores/userDataStore.test.ts, apps/hubble/src/storage/stores/userDataStore.ts, apps/hubble/src/storage/stores/verificationStore.test.ts, apps/hubble/src/storage/stores/verificationStore.ts, apps/hubble/src/test/bench/syncEngine.ts
Pruning and revoking messages should happen gradually and not clog the commit queue.
* Only allow one event to be committed at a time
* Break pruning and revoking messages up into many commits
* Ensure prune and revoke iterators are closed, even if there is a failure
* Move revoking of UserDataAdd messages when fnames are transferred into engine
=> feat: commit one event at a time

apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts
When an unexpected rejection or exception occurs, attempt to clean shutdown first before force-exiting
- Attempt clean shutdown with errors
- Rebuild sync trie if previous shutdown was not clean
=> fix: Attempt cleanshutdown on unexpected exceptions

apps/hubble/.config/hub.config.ts, apps/hubble/src/cli.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/rpc/server.ts
Dynamically recover from sync trie corruption. 
- Check outgoing messages to remove unavailable messages from the sync trie. 
=> feat: Dynamically recover from syncTrie corruption

apps/hubble/src/console/console.ts, apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/periodicSyncJob.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts
Two bug fixes:
1. Sync stalls when client is not responding
2. Get a write lock when unloading the merkle trie
- Set deadline when calling RPC methods
- Get a write lock when unloading the merkle trie, so as to not run into a deadlock
- Improve logging
=> fix: Sync stalls when peer is not responding

.changeset/chilly-bats-kneel.md, apps/hubble/src/cli.ts, apps/hubble/src/console/console.ts, apps/hubble/src/hubble.ts, packages/hub-nodejs/README.md, packages/hub-nodejs/docs/Client.md, packages/hub-nodejs/examples/chron-feed/index.ts, packages/hub-nodejs/examples/write-data/index.ts, packages/hub-nodejs/src/index.test.ts, packages/protobufs/src/index.ts, packages/utils/src/client.ts
Using `getHubRpcClient` can be slow because it attempts a SSL connection first, and has to wait for a timeout. Update the docs to use `getSSLHubRpcClient` or `getInsecureHubRpcClient` directly. 
- Update docs
=> docs: Use SSL or Insecure clients in examples

apps/hubble/src/utils/periodicTestDataJob.ts
If on testnet, generate test data every 10s
=> chore: bump test data generation time to 10s

apps/hubble/src/network/sync/merkleTrie.test.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/storage/engine/index.ts
This fixes a bug in sync where due to getting recursive snapshots, they were slightly different, causing some messages
to not sync
- Get divergence prefix without the trie
- Don't do recursive snapshots
=> fix: Don't get recursive snapshots

CONTRIBUTING.md
Documenting manual processes.
Add documentation for release instructions.
No changeset for docs prs
=> docs: release instructions

apps/hubble/src/network/sync/syncEngine.ts
Make sync logs more accurate and easy to understand
- Fixed log to clarify that the state is equal to or greater, instead of just greater
- Replaced incorrect use of node with hub, since node refers to trie node and hub refers to hubble instance
No changeset necessary for a small logging change.
=> chore(hubble): make syncEngine logs and docs easier to understand

apps/hubble/src/storage/engine/index.ts, apps/hubble/src/storage/jobs/revokeMessagesBySignerJob.ts, apps/hubble/src/storage/stores/castStore.ts, apps/hubble/src/storage/stores/reactionStore.ts, apps/hubble/src/storage/stores/signerStore.ts, apps/hubble/src/storage/stores/userDataStore.ts, apps/hubble/src/storage/stores/verificationStore.ts
Right now if we encounter an error when pruning or revoking a list of messages, the function ends and returns the error. That's suboptimal, because it can result in abandoned messages that should have been revoked but aren't until they're eventually pruned.
* Update `pruneMessages` in all stores to log an error and continue
* Update `revokeMessagesBySigner` in engine to log an error for failures and continue until the iterator is finished
=> chore: update revoke and pruning to continue after error for a single record

.changeset/nervous-masks-camp.md, apps/hubble/src/hubble.ts, apps/hubble/src/storage/db/types.ts
Fixed #771
Write the network ID into the DB, so it can't accidentally be started on a different network
- Write network ID into DB
- Refuse to startup if network doesn't match
=> fix: Refuse to startup if DB is mismatched

apps/hubble/src/storage/engine/index.test.ts, apps/hubble/src/storage/engine/index.ts
Addresses an edge case where a UserDataAdd fname should be revoked when an fid is transferred, because the custody address for the fid and fname are no longer the same.
* Add an extra check to the `handleMergeIdRegistryEvent` engine callback
=> feat: revoke UserDataAdd for fname when fid transfers

apps/hubble/src/network/sync/periodicSyncJob.ts
Start the sync job at :45 seconds, so as to not clash with the prune job at the top of the hour
- Start sync job slightly after prune job
=> chore: shift timing of sync job

.changeset/honest-frogs-watch.md, apps/hubble/src/cli.ts, apps/hubble/src/rpc/adminServer.ts, apps/hubble/src/rpc/server.ts, apps/hubble/src/utils/periodicTestDataJob.ts
We need to support multiple usernames and passwords for RPC Authentication
- RPC_AUTH now accepts a series of usernames and passwords, separated by commas
=> fix: Support multiple RPC usernames

apps/hubble/src/cli.ts, apps/hubble/src/rpc/server.ts
Make sure there are no duplicates in RPC_AUTH usernames
=> fix: Make sure there are no duplicate rpc usernames

apps/hubble/src/rpc/adminServer.ts, apps/hubble/src/rpc/server.ts, apps/hubble/src/utils/periodicTestDataJob.ts
Allow multiple passwords for a rpc user so that passwords can be rotated more easily. 
- Allow multiple passwords per user.
=> fix: allow multiple passwords for a rpc user

.changeset/gold-points-leave.md, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/utils/periodicTestDataJob.ts
Fix a memory leak where rpc client connections were not being closed
- Close RPC connections before finishing sync. 
=> handle errors

.changeset/gold-points-leave.md, .changeset/honest-frogs-watch.md, .changeset/nervous-masks-camp.md, .changeset/sour-experts-poke.md, .changeset/tricky-suits-carry.md, apps/hubble/CHANGELOG.md, apps/hubble/package.json
Release v1.0.19 of hubble
- Release
- fe74a1e: Close RPC connections to fix a memory leak
- 1025d3b: Support multiple RPC users via comma-separted-list
- de25020: Refuse to startup if DB network is mismatched
- 58cfbb9: Gossip server listens on 0.0.0.0 by default
- 9ee1076: Better grpc error messages when auth fails
=> Release v1.0.19 of hubble

.changeset/kind-wasps-fly.md, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/utils/crypto.ts
Fix an issue with sync where sometimes a branch of the trie wouldn't sync if we had one more message than the other node. 
- Recurse down the tree if the hashes mismatch, till we identify the mismatched node.
=> fix: Sync was sometimes off by 1

.changeset/big-apricots-clean.md, apps/hubble/src/rpc/server.ts, apps/hubble/src/storage/engine/index.ts, apps/hubble/src/storage/stores/signerStore.test.ts, apps/hubble/src/storage/stores/signerStore.ts, packages/protobufs/src/generated/rpc.ts, packages/protobufs/src/schemas/rpc.proto
Right now if you only know a custody address, it's hard to retrieve an fid via gRPC.
* Add a `getIdRegistryEventByAddress` method to `rpc.proto` and hubble (this was already implemented, just not connected to rpc)
=> feat: add getIdRegistryEventByAddress method

.changeset/light-hounds-arrive.md, apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts
Missing IdRegistry events during sync should be retried from the RPC provider instead of fetching it unverified from the peer. 
Fixes #767 
- If a missing IdRegistryEvent is detected, fetch it from the RPC provider
- Verify peer's IP address (and don't crash)
=> fix: Fetch missing IdRegistry from the contract instead of the peer

.changeset/quick-donuts-shave.md, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.ts, apps/hubble/src/network/p2p/periodicPeerCheck.ts, apps/hubble/src/network/sync/periodicSyncJob.ts
If all bootstrap nodes fail to connect, we should retry them 
- Retry bootstrap nodes if no connections
- Check if we have peers every 5 minutes
=> fix: Retry bootstrap nodes if they fail to connect at startup

.changeset/little-bats-lick.md, apps/hubble/src/storage/engine/index.ts
Fix issue where iterator was not ended
end iterator if returning early from forEachMessage
=> fix: End iterator if returning early from forEachMessage

.changeset/thick-tips-invite.md, apps/hubble/src/network/p2p/gossipNode.test.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/rpc/test/bulkService.test.ts, apps/hubble/src/rpc/test/castService.test.ts, apps/hubble/src/rpc/test/concurrency.test.ts, apps/hubble/src/rpc/test/reactionService.test.ts, apps/hubble/src/rpc/test/rpcAuth.test.ts, apps/hubble/src/rpc/test/signerService.test.ts, apps/hubble/src/rpc/test/submitService.test.ts, apps/hubble/src/rpc/test/userDataService.test.ts, apps/hubble/src/rpc/test/verificationService.test.ts, apps/hubble/src/utils/periodicTestDataJob.ts, packages/hub-nodejs/README.md, packages/hub-nodejs/docs/Client.md, packages/hub-nodejs/examples/chron-feed/index.ts, packages/hub-nodejs/examples/make-cast/index.ts, packages/hub-nodejs/examples/write-data/index.ts, packages/utils/src/client.ts
Update docs to encourage users to close the grpc client connection after use
- add close() method directly on client
- Update docs to close() connection after every use.
=> docs: update docs to close() grpc connection

.changeset/chilled-cats-wave.md, apps/hubble/src/hubble.ts
To enable the smoke test to run, we should start the rpcServer before the ethEventsProvider
Change startup order
- rpcServer
- ethEventsProvider
- SyncEngine
=> fix: Start the rpc Server before the ethEventsProvider for smoke test

.changeset/tasty-grapes-decide.md, apps/hubble/src/hubble.ts, apps/hubble/src/utils/versions.test.ts, apps/hubble/src/utils/versions.ts, packages/protobufs/src/generated/gossip.ts, packages/protobufs/src/schemas/gossip.proto
followup to [expire hubs](https://github.com/farcasterxyz/hub-monorepo/pull/795)
Ignore outdated hubs when syncing
=> feat: ignore hubs below minimum version for sync

.github/workflows/ci.yml
Ensure we know if we accidentally break the gRPC service for the hub.
Add a simple test to our build step that ensures the gRPC service is running.
=> chore: Test gRPC server is running in Docker image

.github/workflows/ci.yml
The `-e ""` workaround is no longer necessary as of 8e46cac1.
Remove it from our smoke screen test.
=> chore: Remove unnecessary flag for smoke test

.changeset/neat-dingos-fry.md, packages/hub-web/src/client.ts
enable getSSLHubRpcClient for hub-web
enable getSSLHubRpcClient for hub-web
=> chore: enable getSSLHubRpcClient

.changeset/light-gifts-remember.md, packages/hub-web/src/client.ts
Small fix to the hub-web client to ensure we're mapping grpc codes to valid hub error codes
=> fix: map grpc error codes to hub error codes

apps/hubble/src/hubble.ts, apps/hubble/src/utils/versions.test.ts, apps/hubble/src/utils/versions.ts
Fixes hub crashing when version is empty
Version can be empty for older hub versions.
=> fix: handle invalid version strings

.changeset/eighty-buckets-shout.md, apps/hubble/src/hubble.ts, packages/core/src/protobufs/generated/gossip.ts, protobufs/schemas/gossip.proto
Fixes: https://github.com/farcasterxyz/hub-monorepo/issues/835. Prevents testnet hubs from accidentally syncing mainnet and vice versa
Check the peer hubs network and make sure it matches ours before syncing
=> feat: ensure hub networks match when syncing with peers

.changeset/modern-houses-matter.md, apps/hubble/.config/hub.config.ts, apps/hubble/package.json, apps/hubble/src/cli.ts
make dbreset its own command
Remove --db-reset arg
Add dbreset command
=> fix: Make dbreset its own command

.changeset/tiny-pots-collect.md, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.test.ts, apps/hubble/src/network/p2p/gossipNode.ts
Add call to hangup() so we actually disconnect from peers when removing from our addressbook
- Add hangup() when remove from address book 
- Test
=> fix: Hangup on peers when removing from address book

.changeset/nervous-bats-help.md, apps/hubble/src/allowedPeers.mainnet.ts, apps/hubble/src/hubble.ts
Check in the list of allowed peers for Farcaster Mainnet
- `allowedPeers.mainnet.ts` now contains a list of allowed mainnet peers
=> chore: Check in mainnet allowed peers

apps/hubble/src/storage/engine/index.test.ts, packages/core/src/factories.ts
Closes https://github.com/farcasterxyz/hub-monorepo/issues/737
Add a test to make sure it's not possible to pass in a different network in the claim vs the verification and have it pass.
=> chore: Add test to ensure verification and claim must have same network

packages/hub-nodejs/examples/make-cast/index.ts, packages/hub-nodejs/examples/write-data/index.ts
Update example code `make-cast/index.ts` and `write-data/index.ts` to support reaching hubs with authentication
When hubs require username and password, `client.submitMessage` requires an `authMetadata` object. It isn't obvious in the samples how to do this, but it would make it a lot easier if the samples included this. 
I commented out any `authMetadata` code but it can sit there in case someone needs to reference it when they try and replicate the `write-data` process, but not sure if the commented code is a problematic way to add this documentation
N/A
=> docs: update examples for making casts and writing data

.changeset/wicked-planets-walk.md, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/test/bench/syncEngine.ts
First step for https://github.com/farcasterxyz/hub-monorepo/issues/851
Adds a greppable log line that gives us visibility into the hubs sync status. 
=> chore: log sync status for better visibility

.changeset/spotty-dryers-kneel.md, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.ts, apps/hubble/src/network/p2p/protocol.ts, apps/hubble/src/network/utils/factories.ts, apps/hubble/src/test/e2e/gossipNetwork.test.ts
Fixes https://github.com/farcasterxyz/hub-monorepo/issues/860 and https://github.com/farcasterxyz/hub-monorepo/issues/849
- Adds the network id to all gossip topics the hubs subscribes to ensure we're only talking with peers on the same network
Tested manually. Bootstrapped the a node to testnet node and verified it's not receiving any messages from current testnet/mainnet nodes but can receive messages from another instance with the topic change.
=> feat: Include network id in gossip topics to keep networks isolated

.changeset/twelve-files-push.md, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.test.ts, apps/hubble/src/network/sync/merkleTrie.ts, apps/hubble/src/network/sync/mock.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/network/sync/syncEnginePerf.test.ts, apps/hubble/src/rpc/adminServer.ts, apps/hubble/src/rpc/server.ts, apps/hubble/src/rpc/test/bulkService.test.ts, apps/hubble/src/rpc/test/castService.test.ts, apps/hubble/src/rpc/test/concurrency.test.ts, apps/hubble/src/rpc/test/reactionService.test.ts, apps/hubble/src/rpc/test/rpcAuth.test.ts, apps/hubble/src/rpc/test/signerService.test.ts, apps/hubble/src/rpc/test/submitService.test.ts, apps/hubble/src/rpc/test/userDataService.test.ts, apps/hubble/src/rpc/test/verificationService.test.ts, apps/hubble/src/storage/engine/index.ts, apps/hubble/src/test/bench/syncEngine.ts, apps/hubble/src/test/mocks.ts, packages/hub-web/examples/chron-feed/package.json, packages/hub-web/examples/chron-feed/yarn.lock
In trying to diagnose sync behavior, I became frustrated at not having a clearer separation between sync, gossip, and storage. This PR attempts to draw a clearer distinction and use the `Hub` class as a bridge between them all.
* Refactor sync to always merge messages through the hub's `submitMessage` method
* Remove sync-related methods (`forEachMessage` and `getAllMessagesBySyncIds`) from the storage engine
=> chore: re-organize sync engine to use submitMessage rather than mergeMessage

apps/hubble/src/allowedPeers.mainnet.ts
Adding a new peer for discove managed by @df
A new peer ID was added.
Had some problems resetting my hub and I think I backed up my identity incorrectly, so I created a new one
=> chore: add new peerid for @df

.changeset/moody-rocks-greet.md, apps/hubble/src/cli.ts, apps/hubble/src/eth/ethEventsProvider.test.ts, apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts, apps/hubble/src/network/sync/syncEngine.ts, apps/hubble/src/test/mocks.ts
Fixes https://github.com/farcasterxyz/hub-monorepo/issues/892
And helps with https://github.com/farcasterxyz/hub-monorepo/issues/898
There's an off by one error when we retry fetching a id registry event which meant we weren't actually querying the events. This fixes the issue, and adds a flag to trigger a manual resync if desired
=> fix: Fix off by one error when retrying id registry event on sync

packages/hub-nodejs/README.md
In the flagship example for hub-nodejs we are importing `getInsecureHubRpcClient` but using `getSSLHubRpcClient` to instantiate a client.
Edit: I changed it to use `getSSLHubRpcClient` to work with the given URL format. I also changed the fid to be more realistic, as `fid: 2` will not yield any casts on testnet
=> docs(hub-nodejs): update example

CONTRIBUTING.md, apps/hubble/README.md, apps/hubble/src/eth/ethEventsProvider.test.ts
Make it easy for developers to set up Hubs on mainnet
- Remove all incorrect references to flatbuffers
- Added instructions for connecting to mainnet hubs
- Cleaned up many unclear or outdated parts of the documentation
=> docs(hubble): add instructions for connecting to mainnet

packages/hub-nodejs/examples/chron-feed/README.md, packages/hub-nodejs/examples/chron-feed/index.ts, packages/hub-nodejs/examples/chron-feed/package.json, packages/hub-nodejs/examples/chron-feed/yarn.lock, packages/hub-web/examples/chron-feed/index.ts
Fixes issues with the chron feed examples
- Added URLs for mainnet hubs directly into examples
- Added URls for repos 
No changeset for example PRs
=> chore(hub-nodejs): add hub urls, steps to chron-feed examples

apps/hubble/README.md
Docs should not need to be updated manually with every release
- Added a `@farcaster/hubble@latest` tag to v1.2.0 
- Updated docs to pull from this `latest` tag instead of a specific version
Going forward, releases will need to be tagged with `latest` whenever they are released.
=> docs(hubble): use hubble/latest instead of a specific version

README.md, apps/hubble/README.md
Address instances running out of space and having databases corrupted.
- Add pm2 logrotate to recommended setup which prunes log files
- Add exponential backoff to restart attempts to prevent db corruption when shutdown is messy
=> docs(hubble): add pm2 logrotate, exponential backoff to address failures

packages/hub-nodejs/examples/replicate-data-postgres/db.ts, packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts, packages/hub-nodejs/examples/replicate-data-postgres/migrations/002_add_hash_to_links.ts
Right now every table has a `hash` column, so this is just making the `links` table consistent
Added property, added migration
=> feat: Add hash to links table in postgres replicator

.changeset/slow-roses-dream.md, apps/hubble/src/eth/ethEventsProvider.ts, apps/hubble/src/eth/l2EventsProvider.ts
ID Events are starting to arrive more often, resulting in 10000 block chunks having enough events to sometimes hit lock contention. Reducing this has minimal impact on fresh hub sync time while avoiding lock contention.
Adjusted chunk size to 1000 from 10000.
=> fix: Adjust chunk size to 1000

.changeset/many-games-exist.md, apps/hubble/src/cli.ts, apps/hubble/src/defaultConfig.ts, apps/hubble/src/hubble.ts, apps/hubble/src/network/p2p/gossipNode.ts
Direct peering is useful in certain situations. The gossipsub option should be exposed as hub options.
Adds directPeers as a configurable option either by cli or json config. CLI use:
```--direct-peers /ip4/45.58.32.111/tcp/2282/p2p/12D3KooWN9ztVoHYi26NwTDDLNjgBozz479br3pwBuy3oLQVQmhz```
=> feat: support direct peering

.changeset/tiny-bears-peel.md, apps/hubble/src/storage/stores/store.ts, apps/hubble/src/storage/stores/storeEventHandler.ts
We enabled partial support for rent-based pruning, with the caveat that data for fids with no rent do not get pruned, only warned. Until we are closer to fully migrating to storage rent, let's bump this down to debug instead of warn.
Changes the prune `warning` for rent to `debug`.
=> chore: Adjust rent-based prune warning to debug for now

scripts/hubble.sh
Installing docker on amazon linux fails with:
```
ERROR: Unsupported distribution 'amzn'
```
because the https://get.docker.com script does not support the distro. Fall back to docker-compose in that case.
=> fix: Fallback to docker-compose if docker install fails

.changeset/silver-timers-collect.md, apps/hubble/src/addon/Cargo.lock, apps/hubble/src/addon/Cargo.toml, apps/hubble/src/addon/src/db/multi_chunk_writer.rs, apps/hubble/src/addon/src/db/rocksdb.rs, apps/hubble/src/rustfunctions.ts, apps/hubble/src/storage/jobs/dbSnapshotBackupJob.ts, apps/hubble/src/utils/snapshot.ts
When we're creating a snapshot, we open a fresh DB and write keys to it. For this DB, we don't need the WAL, since it is not a live DB, so we can disable WAL to write keys faster.
- Disable WAL
- Use batched writes
- Compress .tar.gz with 4 threads
=> perf: Disable WAL when creating snapshot

apps/hubble/www/docs/intro/install.md
Running a hub requires more storage than is documented
Change requirements from 40GB to 140GB
=> docs: Edit system requirements for running a hub

docker-compose-multinode.yml
I tried running this multinode setup and ran into a couple issues with the config. This PR fixes them. 
I just added arguments for the optimism rpc url (required) and removed --gossip-metrics-enabled which doesn't exist anymore. 
=> fix: updated multinode docker compose

.changeset/light-cobras-judge.md, apps/hubble/src/defaultConfig.ts
Snapshots are using too much bandwitdh, increase the threshold to about 10% of current messages (~470M)
=> fix: Increase message threshold to reduce snapshot bandwidth usage

.github/workflows/publish.yml
Due to a change in the visibility of the secret, our release process stopped working.
=> Fix variable reference for publish workflow

apps/hubble/www/docs/docs/cli.md, packages/hub-nodejs/docs/Messages.md
Changes:
- Removed duplicate "Snapshots Options" section from CLI documentation as it already exists in the main options list.
Before (appears twice):
Snapshots Options:
--enable-snapshot-to-s3               Enable daily snapshots to be uploaded to S3. (default: disabled)
--s3-snapshot-bucket <bucket>         The S3 bucket to upload snapshots to
--disable-snapshot-sync               Disable syncing from snapshots. (default: enabled)
File changed: apps/hubble/www/docs/docs/cli.md
Screenshot needed:
=> Remove duplicate Snapshots Options section
